<?php
/**
 * This file is part of the Magebit_Bizaar package.
 *
 * @copyright Copyright (c) 2023 Magebit, Ltd. (https://magebit.com/)
 * @author Magebit <info@magebit.com>
 */

declare(strict_types=1);

/**
 * Initialize bizaar namespace where we will store global custom functionality for Hyva
 */
?>
<script>
    'use strict';
    (function( bizaar ) {

    }( window.bizaar = window.bizaar || {} ));
</script>
