<?php
/**
 * This file is part of the Magebit_Bizaar package.
 *
 * @copyright Copyright (c) 2024 Magebit, Ltd. (https://magebit.com/)
 * @author Magebit <info@magebit.com>
 */
?>
<script>
    "use strict";

    (function () {
        window.bizaar.initLayeredNavigationItem = function (options) {
            return {
                showLimit: 5,
                showMore: false,
                count: options.count
            }
        }
    })();
</script>
