<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Hyva Compatibility
 */

use Amasty\RequestQuote\Block\Product\Action;
use Amasty\RequestQuoteHyva\ViewModel\QuoteIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var Action $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$quoteIcons = $viewModels->require(QuoteIcons::class);
$buttonClasses = '';
$buttonClasses .= $block->isProductListing()
    ? ' mt-3'
    : ' mt-0';
$buttonClasses .= $block->getLoggedIn()
    ? ''
    : ' amasty-quote-login';
$textClasses = $block->isProductListing()
    ? 'ml-2 inline md:ml-0 lg:ml-2 lg:inline'
    : 'sm:block lg:block';
?>
<?php
$isProductListing = (bool)$block->isProductListing();
if ($this->getRequest()->getFullActionName() == 'cms_index_index') {
 $isProductListing = true;
}
?>
<?php 
$hidePriceHelper = $this->helper('\Amasty\HidePrice\Helper\Data');
if (!$hidePriceHelper->isNeedHideProduct($block->getProduct()))
{
?>
<button x-data="initAmQuoteButton(
            '<?= $escaper->escapeUrl($block->getAddUrl()); ?>',
            <?= /** @noEscape */ var_export($isProductListing, true) ?>,
            <?= /** @noEscape */ var_export((bool)$block->getLoggedIn(), true) ?>
        )"
        x-init="initButton($el)"
        @click.prevent="submitQuote($el)"
        <?php if (!$isProductListing): ?>
            form="product_addtocart_form"
        <?php endif; ?>
        type="button"
        title="<?= $escaper->escapeHtmlAttr($block->getButtonText()) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr($block->getButtonText()) ?>"
        class="amquote-addto-button btn add-to-quote btn-primary btn-light px-6 <?= /** @noEscape */$buttonClasses ?>">    
    <span class="amquote-addto-button-text <?= /** @noEscape */ $textClasses ?>"><?= $escaper->escapeHtml($block->getButtonText()) ?></span>
</button>
<?php } ?>
