<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>

<div>
    <button id="generate_gtm_api_json" 
    title="<?= /* @noEscape */ __("Generate Triggers and Tags Json Format") ?>" 
    type="button" 
    class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" 
    role="button" 
    aria-disabled="false">
        <span class="ui-button-text">
            <span><?= /* @noEscape */  __("Generate") ?></span>
        </span>
    </button>
    <button id="download_gtm_json"
    onclick="location.href='<?= /* @noEscape */ $block->getPathJsonSentData() ?>'"
    type="button"
    class="action-default scalable ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
    role="button"
    aria-disabled="false">
        <span class="ui-button-text">
            <span><?= /* @noEscape */ __("Download File") ?></span>
        </span>
    </button>
    <input type="hidden" value="<?= /* @noEscape */ $block->getFormKey(); ?>" name="api_form_key" id="api_form_key" />
</div>
<!-- Start of MageDelight GA4 Extension -->
<script>
    requirejs(['jquery', 'Magedelight_Ga4/js/ga4Api' ],
        function   ($, ga4Api) {
            $(document).ready(function() {
                ga4Api.initializeJsonGeneration('<?= /* @noEscape */ $block->getPathForJsonData() ?>');
            });
        });
</script>
<!-- End of MageDelight GA4 Extension -->