<?php

use Hyva\Theme\ViewModel\ReCaptcha;

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var ReCaptcha $recaptcha|null 
 */

$customFormBlock = $block->getLayout()->createBlock('Ktpl\CustomForms\Block\CustomForms');
$customFormHelper = $this->helper('Ktpl\CustomForms\Helper\Data');

$recaptcha = $block->getData('viewModelRecaptcha');
?>

<!-- <script src="https://www.google.com/recaptcha/api.js" type="text/javascript" xml="space"></script> -->

<div id="request_quote_container">
    <form class="form request card lg:w-1/2 mb-8" action="<?= $customFormBlock->getFormAction(); ?>" id="request_quote"
        method="post" x-data="initRequestForm()" @submit.prevent="submitForm()" enctype="multipart/form-data">
        <fieldset>
            <input type="hidden" name="form_name" value="request_quote" />
            <input name="username" type="hidden" value="">

            <?php echo $this->getBlockHtml('formkey') ?>

            <div class="field field-reserved name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                        class="input-text form-input" type="text" required />
                </div>
            </div>

            <div class="field field-reserved companyname">
                <label class="label"
                    for="companyname"><span><?= $block->escapeHtml(__('Company Name')) ?></span></label>
                <div class="control">
                    <input name="companyname" id="companyname" title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>"
                        class="input-text form-input" type="text" data-validate="{input_tag_rule:true}" />
                </div>
            </div>

            <div class="field field-reserved email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                        class="input-text form-input" type="email" required />
                </div>
            </div>

            <div class="field field-reserved phonenumber required">
                <label class="label"
                    for="phonenumber"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control flex gap-3">
                    <select name="SbCFPTelPrefix" id="SbCFPTelPrefix" class="form-select w-[120px]" required></select>
                    <input name="phonenumber" id="phonenumber" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                        class="input-text form-input" required autocomplete="off" />
                    <span class="phonenumber-error" id="phonenumber-error"></span>
                </div>
            </div>

            <div class="field field-reserved shippingaddress required">
                <label class="label"
                    for="shippingaddress"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></label>
                <span><?= $block->escapeHtml(__('Street Address, City, State, ZIP')) ?></span>

                <div class="control">
                    <input name="shippingaddress" id="shippingaddress"
                        title="<?= $block->escapeHtmlAttr(__('Shipping Address')) ?>" class="input-text form-input"
                        type="text" required />
                </div>
            </div>
            <div class="field field-reserved productlist required">
                <label class="label" for="productlist">
                    <span><?= $block->escapeHtml(__('Product List')) ?></span>
                </label>
                <span><?= $block->escapeHtml(__('Please Include SKUs and Quantities.')) ?></span>
                <div class="control">
                    <textarea name="productlist" id="productlist"
                        title="<?= $block->escapeHtmlAttr(__('Product List')) ?>" class="input-text form-input" cols="5"
                        rows="3" required></textarea>
                </div>
            </div>
            <div class="field field-reserved additional">
                <label class="label" for="additional">
                    <span><?= $block->escapeHtml(__('Additional Comments')) ?></span>
                </label>
                <div class="control">
                    <textarea name="additional" id="additional"
                        title="<?= $block->escapeHtmlAttr(__('Additional Comments')) ?>" class="input-text form-input"
                        cols="5" rows="3"></textarea>
                </div>
            </div>
            <div class="field field-reserved attachment">
                <label class="label"
                    for="attachment"><span><?= $block->escapeHtml(__('Uploaded File')) ?></span></label>
                <div class="control dropzone-wrapper">

                    <input name="attachment[]" id="attachment" class="dropzone text-sm"
                        accept=".pdf, .doc, .xlsx, .csv, .txt" type="file" multiple="multiple" />
                </div>
                <span id="file-error" style="color: red; display: none;">Invalid file type uploaded!</span>
            </div>

            <div class="form-group required">
                <div class="mb-2">
                    <span>How would you like us to contact you?</span>
                </div>
                <div class="flex gap-3 mb-5">
                    <div class="flex items-center">
                        <input type="checkbox" id="emailoption" name="option">
                        <label for="emailoption" class="clear mb-0 ml-2 text-sm font-semibold">E-mail</label>
                    </div>
                    <div class="flex items-center">
                        <input type="checkbox" id="phoneoption" name="option">
                        <label for="phoneoption" class="clear mb-0 ml-2 text-sm font-semibold">Telephone</label>
                    </div>
                </div>
                <span class="emailphoneoption-error" id="emailphoneoption-error"></span>
            </div>

            <!-- <div class="form-group required">
                <div class="g-recaptcha required" id="recaptcha"
                    data-sitekey="<?php //echo $customFormHelper->getRecaptchaSiteKey(); ?>">
                </div>
                <div style="display:none" id="error-msg">
                    <span><?php //echo __('This is a required field.') ?></span>
                </div>
            </div> -->


        </fieldset>

        <div class="submit-button">
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"
                class="btn action submit btn-primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>

    </form>
</div>


<!-- <script src="<?php //echo $block->getViewFileUrl('Ktpl_CustomForms::js/autocomplete.js'); ?>"></script> -->

<style>
    #hidden_taxupload {
        display: none;
    }
</style>

<script>

    const phoneInput = document.getElementById('phonenumber');
    const phoneError = document.getElementById('phonenumber-error');

    phoneInput.addEventListener('keydown', function (event) {
        const key = event.key;
        if (!/^\d$/.test(key) && key !== 'Backspace') {
            phoneError.innerHTML = "Please enter digits only."
            phoneError.style.color = "red"
            event.preventDefault();
        } else {
            phoneError.innerHTML = ""
        }
    });

    function initRequestForm() {
        const checkboxes = document.querySelectorAll('input[name="option"]');
        const errorMessage = document.getElementById('emailphoneoption-error');
        const fileInput = document.getElementById('attachment');
        const fileError = document.getElementById('file-error');
        const allowedExtensions = ['pdf', 'doc', 'xlsx', 'csv', 'txt'];
        let validFiles = true;
        let validFileSize = true;
        let isChecked = false;

        return {
            errors: 0,

            submitForm() {
                // Do not rename $form, the variable is expected to be declared in the recaptcha output
                const $form = document.querySelector('#request_quote');

                checkboxes.forEach((checkbox) => {
                    if (checkbox.checked) {
                        isChecked = true;
                        errorMessage.textContent = "";
                    }
                });

                if (!isChecked) {
                    errorMessage.textContent = "You must select at least one option.";
                    errorMessage.style.color = "red"
                }

                const files = fileInput.files;
                const maxFileSize = 20 * 1024 * 1024; // 20MB in bytes
                validFiles = true; // Reset validFiles for each validation
                validFileSize = true; // Reset validFileSize for each validation

                for (let i = 0; i < files.length; i++) {
                    const fileExtension = files[i].name.split('.').pop().toLowerCase();
                    const fileSize = files[i].size;

                    if (!allowedExtensions.includes(fileExtension)) {
                        validFiles = false;
                        break;
                    }

                    if (fileSize > maxFileSize) {
                        validFileSize = false;
                        break;
                    }
                }

                if (!validFiles) {
                    fileError.style.display = 'inline';
                    fileError.textContent = "File type must be '.pdf', '.doc', '.xlsx', '.csv', and '.txt'";
                    event.preventDefault();
                } else if (!validFileSize) {
                    fileError.style.display = 'inline';
                    fileError.textContent = "File size must be less than 20MB";
                    event.preventDefault();
                } else {
                    fileError.style.display = 'none';
                    fileError.textContent = "";
                }

                if (this.errors === 0 && isChecked && validFiles && validFileSize) {
                    $form.submit();
                }
            }
        }
    }


    /* FOR CAPTCHA VALIDATION*/
    // function checkCaptcha() {
    //     var captchaResponse = document.getElementById('g-recaptcha-response').value;
    //     var errorMsg = document.getElementById('error-msg');

    //     if (captchaResponse === '') {
    //         errorMsg.style.display = 'block';
    //         errorMsg.style.color = '#df280a';
    //         errorMsg.style.fontSize = '13px';
    //         return false;
    //     } else {
    //         errorMsg.style.display = 'none';
    //     }
    // }

    function bindTelephoneInput() {
        let TelData = [{
            "code": "AD",
            "flag": "🇦🇩",
            "name": "Andorra",
            "tel": "+376"
        },
        {
            "code": "AE",
            "flag": "🇦🇪",
            "name": "United Arab Emirates",
            "tel": "+971"
        },
        {
            "code": "AF",
            "flag": "🇦🇫",
            "name": "Afghanistan",
            "tel": "+93"
        },
        {
            "code": "AG",
            "flag": "🇦🇬",
            "name": "Antigua and Barbuda",
            "tel": "+1-268"
        },
        {
            "code": "AI",
            "flag": "🇦🇮",
            "name": "Anguilla",
            "tel": "+1-264"
        },
        {
            "code": "AL",
            "flag": "🇦🇱",
            "name": "Albania",
            "tel": "+355"
        },
        {
            "code": "AM",
            "flag": "🇦🇲",
            "name": "Armenia",
            "tel": "+374"
        },
        {
            "code": "AO",
            "flag": "🇦🇴",
            "name": "Angola",
            "tel": "+244"
        },
        {
            "code": "AQ",
            "flag": "🇦🇶",
            "name": "Antarctica",
            "tel": "+672"
        },
        {
            "code": "AR",
            "flag": "🇦🇷",
            "name": "Argentina",
            "tel": "+54"
        },
        {
            "code": "AS",
            "flag": "🇦🇸",
            "name": "American Samoa",
            "tel": "+1-684"
        },
        {
            "code": "AT",
            "flag": "🇦🇹",
            "name": "Austria",
            "tel": "+43"
        },
        {
            "code": "AU",
            "flag": "🇦🇺",
            "name": "Australia",
            "tel": "+61"
        },
        {
            "code": "AW",
            "flag": "🇦🇼",
            "name": "Aruba",
            "tel": "+297"
        },
        {
            "code": "AX",
            "flag": "🇦🇽",
            "name": "Aland Islands",
            "tel": "+358-18"
        },
        {
            "code": "AZ",
            "flag": "🇦🇿",
            "name": "Azerbaijan",
            "tel": "+994"
        },
        {
            "code": "BA",
            "flag": "🇧🇦",
            "name": "Bosnia and Herzegovina",
            "tel": "+387"
        },
        {
            "code": "BB",
            "flag": "🇧🇧",
            "name": "Barbados",
            "tel": "+1-246"
        },
        {
            "code": "BD",
            "flag": "🇧🇩",
            "name": "Bangladesh",
            "tel": "+880"
        },
        {
            "code": "BE",
            "flag": "🇧🇪",
            "name": "Belgium",
            "tel": "+32"
        },
        {
            "code": "BF",
            "flag": "🇧🇫",
            "name": "Burkina Faso",
            "tel": "+226"
        },
        {
            "code": "BG",
            "flag": "🇧🇬",
            "name": "Bulgaria",
            "tel": "+359"
        },
        {
            "code": "BH",
            "flag": "🇧🇭",
            "name": "Bahrain",
            "tel": "+973"
        },
        {
            "code": "BI",
            "flag": "🇧🇮",
            "name": "Burundi",
            "tel": "+257"
        },
        {
            "code": "BJ",
            "flag": "🇧🇯",
            "name": "Benin",
            "tel": "+229"
        },
        {
            "code": "BL",
            "flag": "🇧🇱",
            "name": "Saint Barthelemy",
            "tel": "+590"
        },
        {
            "code": "BM",
            "flag": "🇧🇲",
            "name": "Bermuda",
            "tel": "+1-441"
        },
        {
            "code": "BN",
            "flag": "🇧🇳",
            "name": "Brunei",
            "tel": "+673"
        },
        {
            "code": "BO",
            "flag": "🇧🇴",
            "name": "Bolivia",
            "tel": "+591"
        },
        {
            "code": "BQ",
            "flag": "🇧🇶",
            "name": "Bonaire, Saint Eustatius and Saba ",
            "tel": "+599"
        },
        {
            "code": "BR",
            "flag": "🇧🇷",
            "name": "Brazil",
            "tel": "+55"
        },
        {
            "code": "BS",
            "flag": "🇧🇸",
            "name": "Bahamas",
            "tel": "+1-242"
        },
        {
            "code": "BT",
            "flag": "🇧🇹",
            "name": "Bhutan",
            "tel": "+975"
        },
        {
            "code": "BV",
            "flag": "🇧🇻",
            "name": "Bouvet Island",
            "tel": "+47"
        },
        {
            "code": "BW",
            "flag": "🇧🇼",
            "name": "Botswana",
            "tel": "+267"
        },
        {
            "code": "BY",
            "flag": "🇧🇾",
            "name": "Belarus",
            "tel": "+375"
        },
        {
            "code": "BZ",
            "flag": "🇧🇿",
            "name": "Belize",
            "tel": "+501"
        },
        {
            "code": "CA",
            "flag": "🇨🇦",
            "name": "Canada",
            "tel": "+1"
        },
        {
            "code": "CC",
            "flag": "🇨🇨",
            "name": "Cocos Islands",
            "tel": "+61"
        },
        {
            "code": "CD",
            "flag": "🇨🇩",
            "name": "Democratic Republic of the Congo",
            "tel": "+243"
        },
        {
            "code": "CF",
            "flag": "🇨🇫",
            "name": "Central African Republic",
            "tel": "+236"
        },
        {
            "code": "CG",
            "flag": "🇨🇬",
            "name": "Republic of the Congo",
            "tel": "+242"
        },
        {
            "code": "CH",
            "flag": "🇨🇭",
            "name": "Switzerland",
            "tel": "+41"
        },
        {
            "code": "CI",
            "flag": "🇨🇮",
            "name": "Ivory Coast",
            "tel": "+225"
        },
        {
            "code": "CK",
            "flag": "🇨🇰",
            "name": "Cook Islands",
            "tel": "+682"
        },
        {
            "code": "CL",
            "flag": "🇨🇱",
            "name": "Chile",
            "tel": "+56"
        },
        {
            "code": "CM",
            "flag": "🇨🇲",
            "name": "Cameroon",
            "tel": "+237"
        },
        {
            "code": "CN",
            "flag": "🇨🇳",
            "name": "China",
            "tel": "+86"
        },
        {
            "code": "CO",
            "flag": "🇨🇴",
            "name": "Colombia",
            "tel": "+57"
        },
        {
            "code": "CR",
            "flag": "🇨🇷",
            "name": "Costa Rica",
            "tel": "+506"
        },
        {
            "code": "CU",
            "flag": "🇨🇺",
            "name": "Cuba",
            "tel": "+53"
        },
        {
            "code": "CV",
            "flag": "🇨🇻",
            "name": "Cape Verde",
            "tel": "+238"
        },
        {
            "code": "CW",
            "flag": "🇨🇼",
            "name": "Curacao",
            "tel": "+599"
        },
        {
            "code": "CX",
            "flag": "🇨🇽",
            "name": "Christmas Island",
            "tel": "+61"
        },
        {
            "code": "CY",
            "flag": "🇨🇾",
            "name": "Cyprus",
            "tel": "+357"
        },
        {
            "code": "CZ",
            "flag": "🇨🇿",
            "name": "Czech Republic",
            "tel": "+420"
        },
        {
            "code": "DE",
            "flag": "🇩🇪",
            "name": "Germany",
            "tel": "+49"
        },
        {
            "code": "DJ",
            "flag": "🇩🇯",
            "name": "Djibouti",
            "tel": "+253"
        },
        {
            "code": "DK",
            "flag": "🇩🇰",
            "name": "Denmark",
            "tel": "+45"
        },
        {
            "code": "DM",
            "flag": "🇩🇲",
            "name": "Dominica",
            "tel": "+1-767"
        },
        {
            "code": "DO",
            "flag": "🇩🇴",
            "name": "Dominican Republic",
            "tel": "+1-809 and 1-829"
        },
        {
            "code": "DZ",
            "flag": "🇩🇿",
            "name": "Algeria",
            "tel": "+213"
        },
        {
            "code": "EC",
            "flag": "🇪🇨",
            "name": "Ecuador",
            "tel": "+593"
        },
        {
            "code": "EE",
            "flag": "🇪🇪",
            "name": "Estonia",
            "tel": "+372"
        },
        {
            "code": "EG",
            "flag": "🇪🇬",
            "name": "Egypt",
            "tel": "+20"
        },
        {
            "code": "EH",
            "flag": "🇪🇭",
            "name": "Western Sahara",
            "tel": "+212"
        },
        {
            "code": "ER",
            "flag": "🇪🇷",
            "name": "Eritrea",
            "tel": "+291"
        },
        {
            "code": "ES",
            "flag": "🇪🇸",
            "name": "Spain",
            "tel": "+34"
        },
        {
            "code": "ET",
            "flag": "🇪🇹",
            "name": "Ethiopia",
            "tel": "+251"
        },
        {
            "code": "FI",
            "flag": "🇫🇮",
            "name": "Finland",
            "tel": "+358"
        },
        {
            "code": "FJ",
            "flag": "🇫🇯",
            "name": "Fiji",
            "tel": "+679"
        },
        {
            "code": "FK",
            "flag": "🇫🇰",
            "name": "Falkland Islands",
            "tel": "+500"
        },
        {
            "code": "FM",
            "flag": "🇫🇲",
            "name": "Micronesia",
            "tel": "+691"
        },
        {
            "code": "FO",
            "flag": "🇫🇴",
            "name": "Faroe Islands",
            "tel": "+298"
        },
        {
            "code": "FR",
            "flag": "🇫🇷",
            "name": "France",
            "tel": "+33"
        },
        {
            "code": "GA",
            "flag": "🇬🇦",
            "name": "Gabon",
            "tel": "+241"
        },
        {
            "code": "GB",
            "flag": "🇬🇧",
            "name": "United Kingdom",
            "tel": "+44"
        },
        {
            "code": "GD",
            "flag": "🇬🇩",
            "name": "Grenada",
            "tel": "+1-473"
        },
        {
            "code": "GE",
            "flag": "🇬🇪",
            "name": "Georgia",
            "tel": "+995"
        },
        {
            "code": "GF",
            "flag": "🇬🇫",
            "name": "French Guiana",
            "tel": "+594"
        },
        {
            "code": "GG",
            "flag": "🇬🇬",
            "name": "Guernsey",
            "tel": "+44-1481"
        },
        {
            "code": "GH",
            "flag": "🇬🇭",
            "name": "Ghana",
            "tel": "+233"
        },
        {
            "code": "GI",
            "flag": "🇬🇮",
            "name": "Gibraltar",
            "tel": "+350"
        },
        {
            "code": "GL",
            "flag": "🇬🇱",
            "name": "Greenland",
            "tel": "+299"
        },
        {
            "code": "GM",
            "flag": "🇬🇲",
            "name": "Gambia",
            "tel": "+220"
        },
        {
            "code": "GN",
            "flag": "🇬🇳",
            "name": "Guinea",
            "tel": "+224"
        },
        {
            "code": "GP",
            "flag": "🇬🇵",
            "name": "Guadeloupe",
            "tel": "+590"
        },
        {
            "code": "GQ",
            "flag": "🇬🇶",
            "name": "Equatorial Guinea",
            "tel": "+240"
        },
        {
            "code": "GR",
            "flag": "🇬🇷",
            "name": "Greece",
            "tel": "+30"
        },
        {
            "code": "GS",
            "flag": "🇬🇸",
            "name": "South Georgia and the South Sandwich Islands",
            "tel": "+500"
        },
        {
            "code": "GT",
            "flag": "🇬🇹",
            "name": "Guatemala",
            "tel": "+502"
        },
        {
            "code": "GU",
            "flag": "🇬🇺",
            "name": "Guam",
            "tel": "+1-671"
        },
        {
            "code": "GW",
            "flag": "🇬🇼",
            "name": "Guinea-Bissau",
            "tel": "+245"
        },
        {
            "code": "GY",
            "flag": "🇬🇾",
            "name": "Guyana",
            "tel": "+592"
        },
        {
            "code": "HK",
            "flag": "🇭🇰",
            "name": "Hong Kong",
            "tel": "+852"
        },
        {
            "code": "HM",
            "flag": "🇭🇲",
            "name": "Heard Island and McDonald Islands",
            "tel": "+672"
        },
        {
            "code": "HN",
            "flag": "🇭🇳",
            "name": "Honduras",
            "tel": "+504"
        },
        {
            "code": "HR",
            "flag": "🇭🇷",
            "name": "Croatia",
            "tel": "+385"
        },
        {
            "code": "HT",
            "flag": "🇭🇹",
            "name": "Haiti",
            "tel": "+509"
        },
        {
            "code": "HU",
            "flag": "🇭🇺",
            "name": "Hungary",
            "tel": "+36"
        },
        {
            "code": "ID",
            "flag": "🇮🇩",
            "name": "Indonesia",
            "tel": "+62"
        },
        {
            "code": "IE",
            "flag": "🇮🇪",
            "name": "Ireland",
            "tel": "+353"
        },
        {
            "code": "IL",
            "flag": "🇮🇱",
            "name": "Israel",
            "tel": "+972"
        },
        {
            "code": "IM",
            "flag": "🇮🇲",
            "name": "Isle of Man",
            "tel": "+44-1624"
        },
        {
            "code": "IN",
            "flag": "🇮🇳",
            "name": "India",
            "tel": "+91"
        },
        {
            "code": "IO",
            "flag": "🇮🇴",
            "name": "British Indian Ocean Territory",
            "tel": "+246"
        },
        {
            "code": "IQ",
            "flag": "🇮🇶",
            "name": "Iraq",
            "tel": "+964"
        },
        {
            "code": "IR",
            "flag": "🇮🇷",
            "name": "Iran",
            "tel": "+98"
        },
        {
            "code": "IS",
            "flag": "🇮🇸",
            "name": "Iceland",
            "tel": "+354"
        },
        {
            "code": "IT",
            "flag": "🇮🇹",
            "name": "Italy",
            "tel": "+39"
        },
        {
            "code": "JE",
            "flag": "🇯🇪",
            "name": "Jersey",
            "tel": "+44-1534"
        },
        {
            "code": "JM",
            "flag": "🇯🇲",
            "name": "Jamaica",
            "tel": "+1-876"
        },
        {
            "code": "JO",
            "flag": "🇯🇴",
            "name": "Jordan",
            "tel": "+962"
        },
        {
            "code": "JP",
            "flag": "🇯🇵",
            "name": "Japan",
            "tel": "+81"
        },
        {
            "code": "KE",
            "flag": "🇰🇪",
            "name": "Kenya",
            "tel": "+254"
        },
        {
            "code": "KG",
            "flag": "🇰🇬",
            "name": "Kyrgyzstan",
            "tel": "+996"
        },
        {
            "code": "KH",
            "flag": "🇰🇭",
            "name": "Cambodia",
            "tel": "+855"
        },
        {
            "code": "KI",
            "flag": "🇰🇮",
            "name": "Kiribati",
            "tel": "+686"
        },
        {
            "code": "KM",
            "flag": "🇰🇲",
            "name": "Comoros",
            "tel": "+269"
        },
        {
            "code": "KN",
            "flag": "🇰🇳",
            "name": "Saint Kitts and Nevis",
            "tel": "+1-869"
        },
        {
            "code": "KP",
            "flag": "🇰🇵",
            "name": "North Korea",
            "tel": "+850"
        },
        {
            "code": "KR",
            "flag": "🇰🇷",
            "name": "South Korea",
            "tel": "+82"
        },
        {
            "code": "KW",
            "flag": "🇰🇼",
            "name": "Kuwait",
            "tel": "+965"
        },
        {
            "code": "KY",
            "flag": "🇰🇾",
            "name": "Cayman Islands",
            "tel": "+1-345"
        },
        {
            "code": "KZ",
            "flag": "🇰🇿",
            "name": "Kazakhstan",
            "tel": "+7"
        },
        {
            "code": "LA",
            "flag": "🇱🇦",
            "name": "Laos",
            "tel": "+856"
        },
        {
            "code": "LB",
            "flag": "🇱🇧",
            "name": "Lebanon",
            "tel": "+961"
        },
        {
            "code": "LC",
            "flag": "🇱🇨",
            "name": "Saint Lucia",
            "tel": "+1-758"
        },
        {
            "code": "LI",
            "flag": "🇱🇮",
            "name": "Liechtenstein",
            "tel": "+423"
        },
        {
            "code": "LK",
            "flag": "🇱🇰",
            "name": "Sri Lanka",
            "tel": "+94"
        },
        {
            "code": "LR",
            "flag": "🇱🇷",
            "name": "Liberia",
            "tel": "+231"
        },
        {
            "code": "LS",
            "flag": "🇱🇸",
            "name": "Lesotho",
            "tel": "+266"
        },
        {
            "code": "LT",
            "flag": "🇱🇹",
            "name": "Lithuania",
            "tel": "+370"
        },
        {
            "code": "LU",
            "flag": "🇱🇺",
            "name": "Luxembourg",
            "tel": "+352"
        },
        {
            "code": "LV",
            "flag": "🇱🇻",
            "name": "Latvia",
            "tel": "+371"
        },
        {
            "code": "LY",
            "flag": "🇱🇾",
            "name": "Libya",
            "tel": "+218"
        },
        {
            "code": "MA",
            "flag": "🇲🇦",
            "name": "Morocco",
            "tel": "+212"
        },
        {
            "code": "MC",
            "flag": "🇲🇨",
            "name": "Monaco",
            "tel": "+377"
        },
        {
            "code": "MD",
            "flag": "🇲🇩",
            "name": "Moldova",
            "tel": "+373"
        },
        {
            "code": "ME",
            "flag": "🇲🇪",
            "name": "Montenegro",
            "tel": "+382"
        },
        {
            "code": "MF",
            "flag": "🇲🇫",
            "name": "Saint Martin",
            "tel": "+590"
        },
        {
            "code": "MG",
            "flag": "🇲🇬",
            "name": "Madagascar",
            "tel": "+261"
        },
        {
            "code": "MH",
            "flag": "🇲🇭",
            "name": "Marshall Islands",
            "tel": "+692"
        },
        {
            "code": "MK",
            "flag": "🇲🇰",
            "name": "Macedonia",
            "tel": "+389"
        },
        {
            "code": "ML",
            "flag": "🇲🇱",
            "name": "Mali",
            "tel": "+223"
        },
        {
            "code": "MM",
            "flag": "🇲🇲",
            "name": "Myanmar",
            "tel": "+95"
        },
        {
            "code": "MN",
            "flag": "🇲🇳",
            "name": "Mongolia",
            "tel": "+976"
        },
        {
            "code": "MO",
            "flag": "🇲🇴",
            "name": "Macao",
            "tel": "+853"
        },
        {
            "code": "MP",
            "flag": "🇲🇵",
            "name": "Northern Mariana Islands",
            "tel": "+1-670"
        },
        {
            "code": "MQ",
            "flag": "🇲🇶",
            "name": "Martinique",
            "tel": "+596"
        },
        {
            "code": "MR",
            "flag": "🇲🇷",
            "name": "Mauritania",
            "tel": "+222"
        },
        {
            "code": "MS",
            "flag": "🇲🇸",
            "name": "Montserrat",
            "tel": "+1-664"
        },
        {
            "code": "MT",
            "flag": "🇲🇹",
            "name": "Malta",
            "tel": "+356"
        },
        {
            "code": "MU",
            "flag": "🇲🇺",
            "name": "Mauritius",
            "tel": "+230"
        },
        {
            "code": "MV",
            "flag": "🇲🇻",
            "name": "Maldives",
            "tel": "+960"
        },
        {
            "code": "MW",
            "flag": "🇲🇼",
            "name": "Malawi",
            "tel": "+265"
        },
        {
            "code": "MX",
            "flag": "🇲🇽",
            "name": "Mexico",
            "tel": "+52"
        },
        {
            "code": "MY",
            "flag": "🇲🇾",
            "name": "Malaysia",
            "tel": "+60"
        },
        {
            "code": "MZ",
            "flag": "🇲🇿",
            "name": "Mozambique",
            "tel": "+258"
        },
        {
            "code": "NA",
            "flag": "🇳🇦",
            "name": "Namibia",
            "tel": "+264"
        },
        {
            "code": "NC",
            "flag": "🇳🇨",
            "name": "New Caledonia",
            "tel": "+687"
        },
        {
            "code": "NE",
            "flag": "🇳🇪",
            "name": "Niger",
            "tel": "+227"
        },
        {
            "code": "NF",
            "flag": "🇳🇫",
            "name": "Norfolk Island",
            "tel": "+672"
        },
        {
            "code": "NG",
            "flag": "🇳🇬",
            "name": "Nigeria",
            "tel": "+234"
        },
        {
            "code": "NI",
            "flag": "🇳🇮",
            "name": "Nicaragua",
            "tel": "+505"
        },
        {
            "code": "NL",
            "flag": "🇳🇱",
            "name": "Netherlands",
            "tel": "+31"
        },
        {
            "code": "NO",
            "flag": "🇳🇴",
            "name": "Norway",
            "tel": "+47"
        },
        {
            "code": "NP",
            "flag": "🇳🇵",
            "name": "Nepal",
            "tel": "+977"
        },
        {
            "code": "NR",
            "flag": "🇳🇷",
            "name": "Nauru",
            "tel": "+674"
        },
        {
            "code": "NU",
            "flag": "🇳🇺",
            "name": "Niue",
            "tel": "+683"
        },
        {
            "code": "NZ",
            "flag": "🇳🇿",
            "name": "New Zealand",
            "tel": "+64"
        },
        {
            "code": "OM",
            "flag": "🇴🇲",
            "name": "Oman",
            "tel": "+968"
        },
        {
            "code": "PA",
            "flag": "🇵🇦",
            "name": "Panama",
            "tel": "+507"
        },
        {
            "code": "PE",
            "flag": "🇵🇪",
            "name": "Peru",
            "tel": "+51"
        },
        {
            "code": "PF",
            "flag": "🇵🇫",
            "name": "French Polynesia",
            "tel": "+689"
        },
        {
            "code": "PG",
            "flag": "🇵🇬",
            "name": "Papua New Guinea",
            "tel": "+675"
        },
        {
            "code": "PH",
            "flag": "🇵🇭",
            "name": "Philippines",
            "tel": "+63"
        },
        {
            "code": "PK",
            "flag": "🇵🇰",
            "name": "Pakistan",
            "tel": "+92"
        },
        {
            "code": "PL",
            "flag": "🇵🇱",
            "name": "Poland",
            "tel": "+48"
        },
        {
            "code": "PM",
            "flag": "🇵🇲",
            "name": "Saint Pierre and Miquelon",
            "tel": "+508"
        },
        {
            "code": "PN",
            "flag": "🇵🇳",
            "name": "Pitcairn",
            "tel": "+870"
        },
        {
            "code": "PR",
            "flag": "🇵🇷",
            "name": "Puerto Rico",
            "tel": "+1-787 and 1-939"
        },
        {
            "code": "PS",
            "flag": "🇵🇸",
            "name": "Palestinian Territory",
            "tel": "+970"
        },
        {
            "code": "PT",
            "flag": "🇵🇹",
            "name": "Portugal",
            "tel": "+351"
        },
        {
            "code": "PW",
            "flag": "🇵🇼",
            "name": "Palau",
            "tel": "+680"
        },
        {
            "code": "PY",
            "flag": "🇵🇾",
            "name": "Paraguay",
            "tel": "+595"
        },
        {
            "code": "QA",
            "flag": "🇶🇦",
            "name": "Qatar",
            "tel": "+974"
        },
        {
            "code": "RE",
            "flag": "🇷🇪",
            "name": "Reunion",
            "tel": "+262"
        },
        {
            "code": "RO",
            "flag": "🇷🇴",
            "name": "Romania",
            "tel": "+40"
        },
        {
            "code": "RS",
            "flag": "🇷🇸",
            "name": "Serbia",
            "tel": "+381"
        },
        {
            "code": "RU",
            "flag": "🇷🇺",
            "name": "Russia",
            "tel": "+7"
        },
        {
            "code": "RW",
            "flag": "🇷🇼",
            "name": "Rwanda",
            "tel": "+250"
        },
        {
            "code": "SA",
            "flag": "🇸🇦",
            "name": "Saudi Arabia",
            "tel": "+966"
        },
        {
            "code": "SB",
            "flag": "🇸🇧",
            "name": "Solomon Islands",
            "tel": "+677"
        },
        {
            "code": "SC",
            "flag": "🇸🇨",
            "name": "Seychelles",
            "tel": "+248"
        },
        {
            "code": "SD",
            "flag": "🇸🇩",
            "name": "Sudan",
            "tel": "+249"
        },
        {
            "code": "SE",
            "flag": "🇸🇪",
            "name": "Sweden",
            "tel": "+46"
        },
        {
            "code": "SG",
            "flag": "🇸🇬",
            "name": "Singapore",
            "tel": "+65"
        },
        {
            "code": "SH",
            "flag": "🇸🇭",
            "name": "Saint Helena",
            "tel": "+290"
        },
        {
            "code": "SI",
            "flag": "🇸🇮",
            "name": "Slovenia",
            "tel": "+386"
        },
        {
            "code": "SJ",
            "flag": "🇸🇯",
            "name": "Svalbard and Jan Mayen",
            "tel": "+47"
        },
        {
            "code": "SK",
            "flag": "🇸🇰",
            "name": "Slovakia",
            "tel": "+421"
        },
        {
            "code": "SL",
            "flag": "🇸🇱",
            "name": "Sierra Leone",
            "tel": "+232"
        },
        {
            "code": "SM",
            "flag": "🇸🇲",
            "name": "San Marino",
            "tel": "+378"
        },
        {
            "code": "SN",
            "flag": "🇸🇳",
            "name": "Senegal",
            "tel": "+221"
        },
        {
            "code": "SO",
            "flag": "🇸🇴",
            "name": "Somalia",
            "tel": "+252"
        },
        {
            "code": "SR",
            "flag": "🇸🇷",
            "name": "Suriname",
            "tel": "+597"
        },
        {
            "code": "SS",
            "flag": "🇸🇸",
            "name": "South Sudan",
            "tel": "+211"
        },
        {
            "code": "ST",
            "flag": "🇸🇹",
            "name": "Sao Tome and Principe",
            "tel": "+239"
        },
        {
            "code": "SV",
            "flag": "🇸🇻",
            "name": "El Salvador",
            "tel": "+503"
        },
        {
            "code": "SX",
            "flag": "🇸🇽",
            "name": "Sint Maarten",
            "tel": "+599"
        },
        {
            "code": "SY",
            "flag": "🇸🇾",
            "name": "Syria",
            "tel": "+963"
        },
        {
            "code": "SZ",
            "flag": "🇸🇿",
            "name": "Swaziland",
            "tel": "+268"
        },
        {
            "code": "TC",
            "flag": "🇹🇨",
            "name": "Turks and Caicos Islands",
            "tel": "+1-649"
        },
        {
            "code": "TD",
            "flag": "🇹🇩",
            "name": "Chad",
            "tel": "+235"
        },
        {
            "code": "TF",
            "flag": "🇹🇫",
            "name": "French Southern Territories",
            "tel": "+262"
        },
        {
            "code": "TG",
            "flag": "🇹🇬",
            "name": "Togo",
            "tel": "+228"
        },
        {
            "code": "TH",
            "flag": "🇹🇭",
            "name": "Thailand",
            "tel": "+66"
        },
        {
            "code": "TJ",
            "flag": "🇹🇯",
            "name": "Tajikistan",
            "tel": "+992"
        },
        {
            "code": "TK",
            "flag": "🇹🇰",
            "name": "Tokelau",
            "tel": "+690"
        },
        {
            "code": "TL",
            "flag": "🇹🇱",
            "name": "East Timor",
            "tel": "+670"
        },
        {
            "code": "TM",
            "flag": "🇹🇲",
            "name": "Turkmenistan",
            "tel": "+993"
        },
        {
            "code": "TN",
            "flag": "🇹🇳",
            "name": "Tunisia",
            "tel": "+216"
        },
        {
            "code": "TO",
            "flag": "🇹🇴",
            "name": "Tonga",
            "tel": "+676"
        },
        {
            "code": "TR",
            "flag": "🇹🇷",
            "name": "Turkey",
            "tel": "+90"
        },
        {
            "code": "TT",
            "flag": "🇹🇹",
            "name": "Trinidad and Tobago",
            "tel": "+1-868"
        },
        {
            "code": "TV",
            "flag": "🇹🇻",
            "name": "Tuvalu",
            "tel": "+688"
        },
        {
            "code": "TW",
            "flag": "🇹🇼",
            "name": "Taiwan",
            "tel": "+886"
        },
        {
            "code": "TZ",
            "flag": "🇹🇿",
            "name": "Tanzania",
            "tel": "+255"
        },
        {
            "code": "UA",
            "flag": "🇺🇦",
            "name": "Ukraine",
            "tel": "+380"
        },
        {
            "code": "UG",
            "flag": "🇺🇬",
            "name": "Uganda",
            "tel": "+256"
        },
        {
            "code": "UM",
            "flag": "🇺🇲",
            "name": "United States Minor Outlying Islands",
            "tel": "+1"
        },
        {
            "code": "US",
            "flag": "🇺🇸",
            "name": "United States",
            "tel": "+1"
        },
        {
            "code": "UY",
            "flag": "🇺🇾",
            "name": "Uruguay",
            "tel": "+598"
        },
        {
            "code": "UZ",
            "flag": "🇺🇿",
            "name": "Uzbekistan",
            "tel": "+998"
        },
        {
            "code": "VA",
            "flag": "🇻🇦",
            "name": "Vatican",
            "tel": "+379"
        },
        {
            "code": "VC",
            "flag": "🇻🇨",
            "name": "Saint Vincent and the Grenadines",
            "tel": "+1-784"
        },
        {
            "code": "VE",
            "flag": "🇻🇪",
            "name": "Venezuela",
            "tel": "+58"
        },
        {
            "code": "VG",
            "flag": "🇻🇬",
            "name": "British Virgin Islands",
            "tel": "+1-284"
        },
        {
            "code": "VI",
            "flag": "🇻🇮",
            "name": "U.S. Virgin Islands",
            "tel": "+1-340"
        },
        {
            "code": "VN",
            "flag": "🇻🇳",
            "name": "Vietnam",
            "tel": "+84"
        },
        {
            "code": "VU",
            "flag": "🇻🇺",
            "name": "Vanuatu",
            "tel": "+678"
        },
        {
            "code": "WF",
            "flag": "🇼🇫",
            "name": "Wallis and Futuna",
            "tel": "+681"
        },
        {
            "code": "WS",
            "flag": "🇼🇸",
            "name": "Samoa",
            "tel": "+685"
        },
        {
            "code": "YE",
            "flag": "🇾🇪",
            "name": "Yemen",
            "tel": "+967"
        },
        {
            "code": "YT",
            "flag": "🇾🇹",
            "name": "Mayotte",
            "tel": "+262"
        },
        {
            "code": "ZA",
            "flag": "🇿🇦",
            "name": "South Africa",
            "tel": "+27"
        },
        {
            "code": "ZM",
            "flag": "🇿🇲",
            "name": "Zambia",
            "tel": "+260"
        },
        {
            "code": "ZW",
            "flag": "🇿🇼",
            "name": "Zimbabwe",
            "tel": "+263"
        }
        ]
        let telPrefixes = ``;
        let countryOptions = ``;
        TelData.forEach(item => {
            telPrefixes += `<option value="${item.code}"  ${item.code === 'AE' ? 'selected' : ''} >${item.flag} ${item.tel}</option>`;
            countryOptions += `<option value="${item.code}">${item.flag} ${item.name}</option>`;
        })
        document.getElementById('SbCFPTelPrefix').innerHTML = telPrefixes;
    }
    bindTelephoneInput();
</script>