<?php
/**
 * This file is part of the Magebit_Bizaar package.
 *
 * @copyright Copyright (c) 2023 Magebit, Ltd. (https://magebit.com/)
 * @author Magebit <info@magebit.com>
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */

// Dispatch event to load external scripts after the first user interaction
?>
<script>
    (events => {
        const dispatchUserInteractionEvent = () => {
            events.forEach(type => window.removeEventListener(type, dispatchUserInteractionEvent));
            window.dispatchEvent(new Event('init-external-scripts'));
        };
        events.forEach(type => window.addEventListener(type, dispatchUserInteractionEvent, {once: true, passive: true}));
    })(['touchstart', 'mouseover', 'wheel', 'scroll', 'keydown']);
</script>
