<?php
    /**@var Sparsh\ProductAttachment\ViewModel\Product\View $viewModel*/
    $viewModel = $block->getData('view_model');
    $title = $viewModel->getConfigValue('productattachment/general/title');
    $sortOrder = $viewModel->getConfigValue('productattachment/general/sort_order');
    $block->setData('title', $title);
    $block->setData('sort_order', $sortOrder);
    $attachmentList = $viewModel->getAttachments();
    $mediaPath = $viewModel->getAttachmentMediaPath()."sparsh/product_attachment/";
    $count =  $attachmentList->getSize();
?>
<?php if ($count > 0): ?>
    <ul class="footer links" style="margin:0px;padding-left: 18px;">
        <?php foreach ($attachmentList->getData() as $attachment): ?>
            <?php if (!empty($attachment['title']) && (!empty($attachment['attach_file']))): ?>
                <?php $fileurl = $mediaPath . $attachment['attach_file'] ?>
                <li><a href="<?= /* @noEscape */
                    __($fileurl); ?>" target="_blank"><?= /* @noEscape */
                        __($attachment['title']); ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
