<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
    <div class="post-list-wrapper blog-widget-recent homepage-blogpost">
        <h2 class="title flex justify-between items-center text-lg lg:text-3xl"><?= $block->escapeHtml($block->getTitle()) ?>
            <a href="<?php echo $block->getUrl('blog'); ?>" class="clear text-lg text-[#788793] font-normal"><span><?php echo __('View More Blogs') ?><i class="icon icon-arrow-right"></i></span></a>
        </h2>
        <ul class="post-list clearfix">
            <?php
            $counter = 0;
            foreach ($_postCollection as $_post) { ?>
                <?php
                $_postUrl = $block->escapeUrl($_post->getPostUrl());
                $_postName = $block->escapeHtml($_post->getTitle());
                ?>
                <?php
                if ($counter === 0) { ?>
                    <li class="post-holder firstpost post-holder-<?= (int) $_post->getId() ?>">
                        <div class="post-content">
                            <div class="post-description clearfix md:flex">
                                <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                                <?php if ($featuredImage) { ?>
                                    <?php
                                    $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                    if (!$featuredImgAlt) {
                                        $featuredImgAlt = $_postName;
                                    }
                                    ?>
                                    <div class="post-ftimg-hld">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                            <img src="<?= $block->escapeHtml($featuredImage) ?>"
                                                alt="<?= $block->escapeHtml($featuredImgAlt) ?>" width="886" height="588" />
                                        </a>
                                    </div>
                                <?php } ?>
                                <div class="post-text-hld clearfix md:px-5">
                                    <div class="post-header">
                                        <div class="post-info clear">
                                            <?php if ($_post->isPublishDateEnabled()) { ?>
                                                <div class="item post-posed-date">
                                                    <span class="label"><?= $block->escapeHtml(__('Posted:')) ?></span>
                                                    <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                                </div>
                                            <?php } ?>
                                            <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>

                                            <?php } ?>
                                        </div>
                                        <div class="post-title-holder clearfix">
                                            <div class="post-title">
                                                <a class="post-item-link" href="<?= /*@noEscape*/ $_postUrl ?>">
                                                    <?= /*@noEscape*/ $_postName ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <?= /*@noEscape*/ $block->getShorContent($_post, 50, "...") ?>
                                    <!-- <a class="post-read-more testread"
                                href="<?= /*@noEscape*/ $_postUrl ?>"
                                title="<?= /*@noEscape*/ $_postName ?>"
                                >
                                <?php //$block->escapeHtml(__('Read more &#187;')) ?>
                            </a> -->
                                </div>
                            </div>
                        </div>
                        <div class="post-footer">

                        </div>
                    </li>
                    <?php
                    $counter++;
                }  else {
                    ?>
                    <li class="post-holder post-holder-<?= (int) $_post->getId() ?>">
                        <div class="post-content">
                            <div class="post-description clearfix md:flex">
                                <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                                <?php if ($featuredImage) { ?>
                                    <?php
                                    $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                    if (!$featuredImgAlt) {
                                        $featuredImgAlt = $_postName;
                                    }
                                    ?>
                                    <div class="post-ftimg-hld">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                            <img src="<?= $block->escapeHtml($featuredImage) ?>"
                                                alt="<?= $block->escapeHtml($featuredImgAlt) ?>" width="886" height="588" />
                                        </a>
                                    </div>
                                <?php } ?>
                                <div class="post-text-hld clearfix md:px-5">
                                    <div class="post-header">
                                        <div class="post-info clear">
                                            <?php if ($_post->isPublishDateEnabled()) { ?>
                                                <div class="item post-posed-date">
                                                    <span class="label"><?= $block->escapeHtml(__('Posted:')) ?></span>
                                                    <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                                </div>
                                            <?php } ?>
                                            <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>

                                            <?php } ?>
                                        </div>
                                        <div class="post-title-holder clearfix">
                                            <div class="post-title">
                                                <a class="post-item-link" href="<?= /*@noEscape*/ $_postUrl ?>">
                                                    <?= /*@noEscape*/ $_postName ?>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <?= /*@noEscape*/ $block->getShorContent($_post, 50, "...") ?>
                                    <!-- <a class="post-read-more testread"
                                href="<?= /*@noEscape*/ $_postUrl ?>"
                                title="<?= /*@noEscape*/ $_postName ?>"
                                >
                                <?php //$block->escapeHtml(__('Read more &#187;')) ?>
                            </a> -->
                                </div>
                            </div>
                        </div>
                        <div class="post-footer">

                        </div>
                    </li>
            <?php
            } } ?>
        </ul>
    </div>
<?php } ?>