<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomOption;
use Magento\Catalog\Block\Product\View\Options\Type\Select;
use Magento\Framework\Escaper;

/** @var Select $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$option = $block->getOption();
$product = $block->getProduct();

/** @var CustomOption $customOptionsViewModel */
$customOptionsViewModel = $viewModels->require(CustomOption::class);

?>
<div class="w-full items-center pdp-pro-opt-container mb-5 last:mb-0">
    <label class="block text-base font-normal clear"
           for="select_<?= $escaper->escapeHtmlAttr($option->getId()) ?>"
    >
        <span><?= $escaper->escapeHtml($option->getTitle()) ?></span>
        <?php if ($option->getIsRequire()): ?>
            <span class="sup text-sm">*</span>
        <?php endif; ?>
    </label>
    <div class="text-left w-full">
        <?= $customOptionsViewModel->getOptionHtml($option, $product); ?>
    </div>
</div>
