<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$productDetail = $block->getProduct();
$selectVal = '';
$selectValId = '';
$viewModel = $block->getData('selectItem');

switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $selectVal = __('Related Products');
            $selectValId = 'related_products';
        }
        break;
    case 'related':
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
            $selectVal = __('Related Products');
            $selectValId = 'related_products';
        }
        break;
    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
            $selectVal = __('Upsell Products');
            $selectValId = 'upsell_products';
        }
        break;
    case 'upsell':
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
            $selectVal = __('Upsell Products');
            $selectValId = 'upsell_products';
        }
        break;
    case 'crosssell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();
            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
            $selectVal = __('Crossell Products');
            $selectValId = 'crossell_products';
        }
        break;
    case 'crosssell':
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();
            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
            $selectVal = __('Crossell Products');
            $selectValId = 'crossell_products';
        }
        break;
    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;
            $class = 'widget' . ' ' . $type;
            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;
            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
            $selectVal = __('New Products');
            $selectValId = 'new_products';
        }
        break;
    case 'other':
        break;
}
?>

<?php if ($exist):?>
    <?php if ($type == 'related' || $type == 'upsell' || $type == 'crosssell'): ?>
        <?php if ($type == 'related'): ?>
<div class="block <?=/* @noEscape */ $class; ?>"
    data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
    data-limit="<?=/* @noEscape */ $limit; ?>"
    data-shuffle="<?=/* @noEscape */ $shuffle; ?>">
    <?php elseif ($type == 'upsell'): ?>
    <div class="block <?=/* @noEscape */ $class; ?>"
    data-mage-init='{"upsellProducts":{}}'
    data-limit="<?=/* @noEscape */ $limit; ?>"
    data-shuffle="<?=/* @noEscape */ $shuffle; ?>">
    <?php else: ?>
        <div class="block <?=/* @noEscape */ $class; ?>"
        data-mage-init='{"crosssellProducts":{}}'>   
    <?php endif; ?>
        <?php else: ?>
        <div class="block <?=/* @noEscape */ $class; ?>">
            <?php endif; ?>
            <div class="block-title title">
                <strong id="block-<?=/* @noEscape */ $class?>-heading"
                role="heading"
                aria-level="2">
                <?=/* @noEscape */ $title; ?>
                </strong>
            </div>
            <div class="block-content content"
            aria-labelledby="block-<?=/* @noEscape */ $class?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart): ?>
                    <div class="block-actions">
                        <?= /* @noEscape */__('Check items to add to the cart or') ?>
                        <button type="button" 
                        class="action select" 
                        role="select-all">
                        <span><?= /* @noEscape */__('select all') ?></span></button>
                    </div>
                <?php endif; ?>
                <div class="products wrapper grid products-grid products-<?=/* @noEscape */ $type; ?>">
                    <ol class="products list items product-items">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <?= /* @noEscape */($iterator++ == 1) ?
                                '<li class="item product product-item" style="display: none;">' :
                                '</li><li class="item product product-item" style="display: none;">' ?>
                            <?php else: ?>
                                <?=/* @noEscape */ ($iterator++ == 1) ?
                                '<li class="item product product-item">' :
                                '</li><li class="item product product-item">' ?>
                            <?php endif; ?>
                            <div class="product-item-info <?=/* @noEscape */ $available; ?>">
                                <?=/* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <a <?=/* @noEscape */
                                    $viewModel->selectItem(
                                        $_item,
                                        $iterator-1,
                                        $_item->getName().' '.$selectVal,
                                        $selectValId
                                    );?>
                                    href="<?=/* @noEscape */ $block->getProductUrl($_item) ?>" 
                                    class="product photo product-item-photo">
                                    <?=/* @noEscape */ $block->getImage($_item, $image)->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <strong class="product name product-item-name">
                                <a <?=/* @noEscape */
                                    $viewModel->selectItem(
                                        $_item,
                                        $iterator-1,
                                        $_item->getName().' '.$selectVal,
                                        $selectValId
                                    ); ?>
                                        class="product-item-link" 
                                        title="<?= /* @noEscape */$block->escapeHtml($_item->getName()) ?>" 
                                        href="<?=/* @noEscape */ $block->getProductUrl($_item) ?>">
                                            <?=/* @noEscape */ $block->escapeHtml($_item->getName()) ?></a>
                                    </strong>

                                    <?=/* @noEscape */ $block->getProductPrice($_item); ?>

                                    <?php if ($templateType): ?>
                                        <?=/* @noEscape */ $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($canItemsAddToCart &&
                                        !$_item->isComposite() &&
                                        $_item->isSaleable() &&
                                        $type == 'related'
                                    ): ?>
                                        <?php if (!$_item->getRequiredOptions()): ?>
                                            <div class="field choice related">
                                                <input type="checkbox" 
                                                class="checkbox related" 
                                                id="related-checkbox<?=/* @noEscape */ $_item->getId() ?>" 
                                                name="related_products[]"value="<?=/* @noEscape */$_item->getId() ?>" />
                                                <label class="label" 
                                                for="related-checkbox<?=/* @noEscape */ $_item->getId() ?>">
                                                <span><?=/* @noEscape */ __('Add to Cart') ?>
                                            </span></label>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <?php if ($showAddTo || $showCart): ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()
                                                        ->hasRequiredOptions($_item)):?>
                                                            <button class="action tocart primary"
                                                            data-mage-init='{
                                                                "redirectUrl":
                                                            {
                                                                "url": "
                                                                <?=/* @noEscape */ $block->getAddToCartUrl($_item) ?>"
                                                            }
                                                            }' 
                                                            type="button"
                                                            title="<?=/* @noEscape */ __('Add to Cart') ?>">

                                                                <span><?=/* @noEscape */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php $postDataHelper = $block->postHelper();
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?=/* @noEscape */ $postData; ?>'
                                                                    type="button"
                                                                    title="<?=/* @noEscape */ __('Add to Cart') ?>">
                                                                <span><?=/* @noEscape */  __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available">
                                                                <span><?=/* @noEscape */  __('In stock') ?></span>
                                                            </div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable">
                                                                <span><?=/* @noEscape */ __('Out of stock') ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>

                                            <?php if ($showAddTo): ?>
                                                <div class="secondary-addto-links actions-secondary" 
                                                data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                        <?=/* @noEscape */ $addToBlock
                                                        ->setProduct($_item)->getChildHtml(); ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?=/* @noEscape */ ($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php endif;?>
