<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Hide Price Hyva Compatibility
 */

use Amasty\RequestQuoteHyva\ViewModel\QuoteIcons;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Amasty\HidePriceHyva\ViewModel\Popup;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroIcons = $viewModels->require(HeroiconsOutline::class);
$quoteIcons = $viewModels->require(QuoteIcons::class);
$popup = $viewModels->require(Popup::class);
?>

<div x-data="{...hyva.modal(), ...initAmHidePricePopup()}" x-spread="eventListeners" x-bind="eventListeners">
    <div x-cloak
         x-spread="overlay('am-hideprice-popup')"
         x-bind="overlay('am-hideprice-popup')"
         class="fixed inset-0 flex items-center justify-center text-left bg-black bg-opacity-50 z-40">
        <div x-ref="am-hideprice-popup"
             role="dialog"
             aria-labelledby="am-request-popup-label"
             class="relative inline-block max-h-screen overflow-auto bg-white shadow-xl rounded-lg px-5 pb-5 w-full sm:max-w-screen-sm">
            <div class="flex justify-end w-full my-5">
                <button @click="hide"
                        aria-label="<?= $escaper->escapeHtml(__('Close')) ?>"
                        class="text-black transition hover:text-blue-darker absolute right-0 top-0 p-2 bg-gray-f2">
                    <?= $heroIcons->xHtml('h-6 w-6 p-0.5') ?>
                </button>
            </div>
            <div id="am-request-popup-label" class="w-full pb-2 mb-6 border-b-2 text-black">
                <span><?= $escaper->escapeHtml(__('Get a Price for')) ?></span>
                <span class="font-bold" x-text="formConfig.productName"></span>
            </div>
            <form x-ref="amHidePriceForm" action="#" class="form" @submit.prevent="submitRequest">
                <input type="hidden" name="product_id" :value="formConfig.productId">
                <fieldset class="fieldset">
                    <div class="field w-full field-reserved">
                        <label for="price-request-name">
                            <span class="text-red-500">*</span>
                            <?= $escaper->escapeHtml(__('Customer Name')) ?>
                        </label>
                        <input type="text"
                               required
                               class="w-full form-input"
                               name="name"
                               id="price-request-name"
                               x-model="formConfig.customer.name"
                               x-focus-first/>
                    </div>
                    <div class="field w-full field-reserved">
                        <label for="price-request-email">
                            <span class="text-red-500">*</span>
                            <?= $escaper->escapeHtml(__('Customer Email')) ?>
                        </label>
                        <input type="email"
                               required
                               class="w-full form-input"
                               name="email"
                               id="price-request-email"
                               x-model="formConfig.customer.email"/>
                    </div>
                    <div class="field w-full field-reserved">
                        <label for="price-request-phone">
                            <span class="text-red-500">*</span>
                            <?= $escaper->escapeHtml(__('Phone Number')) ?>
                        </label>
                        <div class="control flex gap-3">
                            <select name="TelPrefix" id="TelPrefix" class="form-select w-[120px]"></select>
                            <input
                                    type="text"
                                    required
                                    class="w-full form-input"
                                    name="phone"
                                    id="price-request-phone"
                                    x-model="formConfig.customer.phone"/>
                        </div>
                    </div>
                    <div class="field w-full field-reserved">
                        <label for="price-request-company">
                            <?= $escaper->escapeHtml(__('Company')) ?>
                        </label>
                        <input
                                type="text"
                                class="w-full form-input"
                                name="company"
                                id="price-request-company"
                                x-model="formConfig.customer.company"/>
                    </div>
                    <div class="field w-full field-reserved">
                        <label for="price-request-quantity">
                            <span class="text-red-500">*</span>
                            <?= $escaper->escapeHtml(__('Quantity')) ?>
                        </label>
                        <input
                                type="number"
                                required
                                class="w-full form-input"
                                name="quantity"
                                id="price-request-quantity"
                                x-model="formConfig.customer.quantity"/>
                    </div>                    
                    <div class="field w-full field-reserved">
                        <label for="price-request-comment">
                            <?= $escaper->escapeHtml(__('Comment')) ?>
                        </label>
                        <textarea name="comment" id="price-request-comment" class="w-full form-input"
                                  rows="3"></textarea>
                    </div>
                    <?php if ($popup->isGDPREnabled()): ?>
                        <div class="field choice">
                            <label for="gdpr" class="am-request-popup-gdpr label">
                                <input type="checkbox"
                                       required
                                       name="gdpr"
                                       value="1"
                                       title="<?= $escaper->escapeHtml(__('GDPR')) ?>"
                                       class="checkbox"/>
                                <span class="text-red-500">*</span>
                                <?= $escaper->escapeHtml($popup->getGDPRText(), ['a', 'br']) ?>
                            </label>
                        </div>
                    <?php endif; ?>
                </fieldset>
                <div x-show="errorMessage.length > 0"
                     x-transition:enter="transition ease-out duration-200"
                     x-transition:enter-start="opacity-0 transform"
                     x-transition:enter-end="opacity-100 transform"
                     class="bg-red-200 p-3 my-3 rounded w-full">
                    <p class="text-red-900" x-text="errorMessage"></p>
                </div>
                <div class="w-full flex">
                    <button
                            :disabled="isLoading"
                            type="submit"
                            class="action submit primary btn btn-primary disabled:opacity-75">
                        <template x-if="!isLoading">
                            <span>
                                <?= $escaper->escapeHtml(__('Submit')) ?>
                            </span>
                        </template>
                        <template x-if="isLoading">
                            <span>
                                <?= $quoteIcons->loadingIndicatorHtml('w-5 h-5 stroke-current') ?> &nbsp;
                                <?= $escaper->escapeHtml(__('Loading...')) ?>
                            </span>
                        </template>
                    </button>
                </div>
            </form>

        </div>

    </div>
</div>

<script>
    'use strict';

    function initAmHidePricePopup() {
        return {
            formConfig: {
                url: '<?= $escaper->escapeUrl($popup->getAddRequestUrl()) ?>',
                productId: null,
                productName: '',
                customer: {
                    name: '<?= $escaper->escapeJs($popup->getCustomerName()) ?>',
                    email: '<?= $escaper->escapeJs($popup->getCustomerEmail()) ?>',
                    phone: '<?= $escaper->escapeJs($popup->getCustomerPhone()) ?>'
                },
            },
            isLoading: false,
            abortController: undefined,
            errorMessage: '',
            eventListeners: {
                ['@open-am-hideprice-popup.window'](event) {
                    this.formConfig = {...this.formConfig, ...event.detail};
                    this.$nextTick(() => {
                        !this.opened['am-hideprice-popup'] && this.show('am-hideprice-popup').then(() => {
                            !!this.abortController && this.abortController.abort();

                            // Wait close animation
                            setTimeout(() => {
                                this.isLoading = false;
                                this.formConfig = {
                                    ...this.formConfig,
                                    productId: null,
                                    productName: null,
                                };
                            }, 400);
                        });
                    });
                }
            },
            submitRequest: function () {
                const headers = {
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
                };
               const TelphoneWithPrefix = document.getElementById('TelPrefix').options[document.getElementById('TelPrefix').selectedIndex].innerHTML.slice(5) + "-" + document.getElementById('price-request-phone').value;
                document.getElementById('price-request-phone').value = TelphoneWithPrefix;

                const form = this.$refs.amHidePriceForm;
                const body = new URLSearchParams(new FormData(form));
                body.append('form_key', hyva.getFormKey());
                this.isLoading = true;
                this.errorMessage = '';
                this.abortController = new AbortController();

                fetch(this.formConfig.url, {
                    signal: this.abortController.signal,
                    method: 'POST',
                    body,
                    headers: headers
                }).then((response) => {
                    if (!response.ok) {
                        this.errorMessage = '<?= $escaper->escapeHtml(__('Something went wrong. Please try again later')) ?>';
                    }

                    return response.json();
                }).then((response) => {
                    if (!response.success) {
                        this.errorMessage = response.error;
                        return;
                    }

                    typeof window.dispatchMessages !== undefined && window.dispatchMessages([{
                        type: 'success',
                        text: response.success
                    }], 5000);

                    form.reset();
                    this.hide('am-hideprice-popup');
                }).finally(() => {
                    this.abortController = undefined;
                    this.isLoading = false;
                });
            }
        }
    }

    function bindTelephoneInput() {
        let TelData = [{
            "code": "AD",
            "flag": "🇦🇩",
            "name": "Andorra",
            "tel": "+376"
        },
        {
            "code": "AE",
            "flag": "🇦🇪",
            "name": "United Arab Emirates",
            "tel": "+971"
        },
        {
            "code": "AF",
            "flag": "🇦🇫",
            "name": "Afghanistan",
            "tel": "+93"
        },
        {
            "code": "AG",
            "flag": "🇦🇬",
            "name": "Antigua and Barbuda",
            "tel": "+1-268"
        },
        {
            "code": "AI",
            "flag": "🇦🇮",
            "name": "Anguilla",
            "tel": "+1-264"
        },
        {
            "code": "AL",
            "flag": "🇦🇱",
            "name": "Albania",
            "tel": "+355"
        },
        {
            "code": "AM",
            "flag": "🇦🇲",
            "name": "Armenia",
            "tel": "+374"
        },
        {
            "code": "AO",
            "flag": "🇦🇴",
            "name": "Angola",
            "tel": "+244"
        },
        {
            "code": "AQ",
            "flag": "🇦🇶",
            "name": "Antarctica",
            "tel": "+672"
        },
        {
            "code": "AR",
            "flag": "🇦🇷",
            "name": "Argentina",
            "tel": "+54"
        },
        {
            "code": "AS",
            "flag": "🇦🇸",
            "name": "American Samoa",
            "tel": "+1-684"
        },
        {
            "code": "AT",
            "flag": "🇦🇹",
            "name": "Austria",
            "tel": "+43"
        },
        {
            "code": "AU",
            "flag": "🇦🇺",
            "name": "Australia",
            "tel": "+61"
        },
        {
            "code": "AW",
            "flag": "🇦🇼",
            "name": "Aruba",
            "tel": "+297"
        },
        {
            "code": "AX",
            "flag": "🇦🇽",
            "name": "Aland Islands",
            "tel": "+358-18"
        },
        {
            "code": "AZ",
            "flag": "🇦🇿",
            "name": "Azerbaijan",
            "tel": "+994"
        },
        {
            "code": "BA",
            "flag": "🇧🇦",
            "name": "Bosnia and Herzegovina",
            "tel": "+387"
        },
        {
            "code": "BB",
            "flag": "🇧🇧",
            "name": "Barbados",
            "tel": "+1-246"
        },
        {
            "code": "BD",
            "flag": "🇧🇩",
            "name": "Bangladesh",
            "tel": "+880"
        },
        {
            "code": "BE",
            "flag": "🇧🇪",
            "name": "Belgium",
            "tel": "+32"
        },
        {
            "code": "BF",
            "flag": "🇧🇫",
            "name": "Burkina Faso",
            "tel": "+226"
        },
        {
            "code": "BG",
            "flag": "🇧🇬",
            "name": "Bulgaria",
            "tel": "+359"
        },
        {
            "code": "BH",
            "flag": "🇧🇭",
            "name": "Bahrain",
            "tel": "+973"
        },
        {
            "code": "BI",
            "flag": "🇧🇮",
            "name": "Burundi",
            "tel": "+257"
        },
        {
            "code": "BJ",
            "flag": "🇧🇯",
            "name": "Benin",
            "tel": "+229"
        },
        {
            "code": "BL",
            "flag": "🇧🇱",
            "name": "Saint Barthelemy",
            "tel": "+590"
        },
        {
            "code": "BM",
            "flag": "🇧🇲",
            "name": "Bermuda",
            "tel": "+1-441"
        },
        {
            "code": "BN",
            "flag": "🇧🇳",
            "name": "Brunei",
            "tel": "+673"
        },
        {
            "code": "BO",
            "flag": "🇧🇴",
            "name": "Bolivia",
            "tel": "+591"
        },
        {
            "code": "BQ",
            "flag": "🇧🇶",
            "name": "Bonaire, Saint Eustatius and Saba ",
            "tel": "+599"
        },
        {
            "code": "BR",
            "flag": "🇧🇷",
            "name": "Brazil",
            "tel": "+55"
        },
        {
            "code": "BS",
            "flag": "🇧🇸",
            "name": "Bahamas",
            "tel": "+1-242"
        },
        {
            "code": "BT",
            "flag": "🇧🇹",
            "name": "Bhutan",
            "tel": "+975"
        },
        {
            "code": "BV",
            "flag": "🇧🇻",
            "name": "Bouvet Island",
            "tel": "+47"
        },
        {
            "code": "BW",
            "flag": "🇧🇼",
            "name": "Botswana",
            "tel": "+267"
        },
        {
            "code": "BY",
            "flag": "🇧🇾",
            "name": "Belarus",
            "tel": "+375"
        },
        {
            "code": "BZ",
            "flag": "🇧🇿",
            "name": "Belize",
            "tel": "+501"
        },
        {
            "code": "CA",
            "flag": "🇨🇦",
            "name": "Canada",
            "tel": "+1"
        },
        {
            "code": "CC",
            "flag": "🇨🇨",
            "name": "Cocos Islands",
            "tel": "+61"
        },
        {
            "code": "CD",
            "flag": "🇨🇩",
            "name": "Democratic Republic of the Congo",
            "tel": "+243"
        },
        {
            "code": "CF",
            "flag": "🇨🇫",
            "name": "Central African Republic",
            "tel": "+236"
        },
        {
            "code": "CG",
            "flag": "🇨🇬",
            "name": "Republic of the Congo",
            "tel": "+242"
        },
        {
            "code": "CH",
            "flag": "🇨🇭",
            "name": "Switzerland",
            "tel": "+41"
        },
        {
            "code": "CI",
            "flag": "🇨🇮",
            "name": "Ivory Coast",
            "tel": "+225"
        },
        {
            "code": "CK",
            "flag": "🇨🇰",
            "name": "Cook Islands",
            "tel": "+682"
        },
        {
            "code": "CL",
            "flag": "🇨🇱",
            "name": "Chile",
            "tel": "+56"
        },
        {
            "code": "CM",
            "flag": "🇨🇲",
            "name": "Cameroon",
            "tel": "+237"
        },
        {
            "code": "CN",
            "flag": "🇨🇳",
            "name": "China",
            "tel": "+86"
        },
        {
            "code": "CO",
            "flag": "🇨🇴",
            "name": "Colombia",
            "tel": "+57"
        },
        {
            "code": "CR",
            "flag": "🇨🇷",
            "name": "Costa Rica",
            "tel": "+506"
        },
        {
            "code": "CU",
            "flag": "🇨🇺",
            "name": "Cuba",
            "tel": "+53"
        },
        {
            "code": "CV",
            "flag": "🇨🇻",
            "name": "Cape Verde",
            "tel": "+238"
        },
        {
            "code": "CW",
            "flag": "🇨🇼",
            "name": "Curacao",
            "tel": "+599"
        },
        {
            "code": "CX",
            "flag": "🇨🇽",
            "name": "Christmas Island",
            "tel": "+61"
        },
        {
            "code": "CY",
            "flag": "🇨🇾",
            "name": "Cyprus",
            "tel": "+357"
        },
        {
            "code": "CZ",
            "flag": "🇨🇿",
            "name": "Czech Republic",
            "tel": "+420"
        },
        {
            "code": "DE",
            "flag": "🇩🇪",
            "name": "Germany",
            "tel": "+49"
        },
        {
            "code": "DJ",
            "flag": "🇩🇯",
            "name": "Djibouti",
            "tel": "+253"
        },
        {
            "code": "DK",
            "flag": "🇩🇰",
            "name": "Denmark",
            "tel": "+45"
        },
        {
            "code": "DM",
            "flag": "🇩🇲",
            "name": "Dominica",
            "tel": "+1-767"
        },
        {
            "code": "DO",
            "flag": "🇩🇴",
            "name": "Dominican Republic",
            "tel": "+1-809 and 1-829"
        },
        {
            "code": "DZ",
            "flag": "🇩🇿",
            "name": "Algeria",
            "tel": "+213"
        },
        {
            "code": "EC",
            "flag": "🇪🇨",
            "name": "Ecuador",
            "tel": "+593"
        },
        {
            "code": "EE",
            "flag": "🇪🇪",
            "name": "Estonia",
            "tel": "+372"
        },
        {
            "code": "EG",
            "flag": "🇪🇬",
            "name": "Egypt",
            "tel": "+20"
        },
        {
            "code": "EH",
            "flag": "🇪🇭",
            "name": "Western Sahara",
            "tel": "+212"
        },
        {
            "code": "ER",
            "flag": "🇪🇷",
            "name": "Eritrea",
            "tel": "+291"
        },
        {
            "code": "ES",
            "flag": "🇪🇸",
            "name": "Spain",
            "tel": "+34"
        },
        {
            "code": "ET",
            "flag": "🇪🇹",
            "name": "Ethiopia",
            "tel": "+251"
        },
        {
            "code": "FI",
            "flag": "🇫🇮",
            "name": "Finland",
            "tel": "+358"
        },
        {
            "code": "FJ",
            "flag": "🇫🇯",
            "name": "Fiji",
            "tel": "+679"
        },
        {
            "code": "FK",
            "flag": "🇫🇰",
            "name": "Falkland Islands",
            "tel": "+500"
        },
        {
            "code": "FM",
            "flag": "🇫🇲",
            "name": "Micronesia",
            "tel": "+691"
        },
        {
            "code": "FO",
            "flag": "🇫🇴",
            "name": "Faroe Islands",
            "tel": "+298"
        },
        {
            "code": "FR",
            "flag": "🇫🇷",
            "name": "France",
            "tel": "+33"
        },
        {
            "code": "GA",
            "flag": "🇬🇦",
            "name": "Gabon",
            "tel": "+241"
        },
        {
            "code": "GB",
            "flag": "🇬🇧",
            "name": "United Kingdom",
            "tel": "+44"
        },
        {
            "code": "GD",
            "flag": "🇬🇩",
            "name": "Grenada",
            "tel": "+1-473"
        },
        {
            "code": "GE",
            "flag": "🇬🇪",
            "name": "Georgia",
            "tel": "+995"
        },
        {
            "code": "GF",
            "flag": "🇬🇫",
            "name": "French Guiana",
            "tel": "+594"
        },
        {
            "code": "GG",
            "flag": "🇬🇬",
            "name": "Guernsey",
            "tel": "+44-1481"
        },
        {
            "code": "GH",
            "flag": "🇬🇭",
            "name": "Ghana",
            "tel": "+233"
        },
        {
            "code": "GI",
            "flag": "🇬🇮",
            "name": "Gibraltar",
            "tel": "+350"
        },
        {
            "code": "GL",
            "flag": "🇬🇱",
            "name": "Greenland",
            "tel": "+299"
        },
        {
            "code": "GM",
            "flag": "🇬🇲",
            "name": "Gambia",
            "tel": "+220"
        },
        {
            "code": "GN",
            "flag": "🇬🇳",
            "name": "Guinea",
            "tel": "+224"
        },
        {
            "code": "GP",
            "flag": "🇬🇵",
            "name": "Guadeloupe",
            "tel": "+590"
        },
        {
            "code": "GQ",
            "flag": "🇬🇶",
            "name": "Equatorial Guinea",
            "tel": "+240"
        },
        {
            "code": "GR",
            "flag": "🇬🇷",
            "name": "Greece",
            "tel": "+30"
        },
        {
            "code": "GS",
            "flag": "🇬🇸",
            "name": "South Georgia and the South Sandwich Islands",
            "tel": "+500"
        },
        {
            "code": "GT",
            "flag": "🇬🇹",
            "name": "Guatemala",
            "tel": "+502"
        },
        {
            "code": "GU",
            "flag": "🇬🇺",
            "name": "Guam",
            "tel": "+1-671"
        },
        {
            "code": "GW",
            "flag": "🇬🇼",
            "name": "Guinea-Bissau",
            "tel": "+245"
        },
        {
            "code": "GY",
            "flag": "🇬🇾",
            "name": "Guyana",
            "tel": "+592"
        },
        {
            "code": "HK",
            "flag": "🇭🇰",
            "name": "Hong Kong",
            "tel": "+852"
        },
        {
            "code": "HM",
            "flag": "🇭🇲",
            "name": "Heard Island and McDonald Islands",
            "tel": "+672"
        },
        {
            "code": "HN",
            "flag": "🇭🇳",
            "name": "Honduras",
            "tel": "+504"
        },
        {
            "code": "HR",
            "flag": "🇭🇷",
            "name": "Croatia",
            "tel": "+385"
        },
        {
            "code": "HT",
            "flag": "🇭🇹",
            "name": "Haiti",
            "tel": "+509"
        },
        {
            "code": "HU",
            "flag": "🇭🇺",
            "name": "Hungary",
            "tel": "+36"
        },
        {
            "code": "ID",
            "flag": "🇮🇩",
            "name": "Indonesia",
            "tel": "+62"
        },
        {
            "code": "IE",
            "flag": "🇮🇪",
            "name": "Ireland",
            "tel": "+353"
        },
        {
            "code": "IL",
            "flag": "🇮🇱",
            "name": "Israel",
            "tel": "+972"
        },
        {
            "code": "IM",
            "flag": "🇮🇲",
            "name": "Isle of Man",
            "tel": "+44-1624"
        },
        {
            "code": "IN",
            "flag": "🇮🇳",
            "name": "India",
            "tel": "+91"
        },
        {
            "code": "IO",
            "flag": "🇮🇴",
            "name": "British Indian Ocean Territory",
            "tel": "+246"
        },
        {
            "code": "IQ",
            "flag": "🇮🇶",
            "name": "Iraq",
            "tel": "+964"
        },
        {
            "code": "IR",
            "flag": "🇮🇷",
            "name": "Iran",
            "tel": "+98"
        },
        {
            "code": "IS",
            "flag": "🇮🇸",
            "name": "Iceland",
            "tel": "+354"
        },
        {
            "code": "IT",
            "flag": "🇮🇹",
            "name": "Italy",
            "tel": "+39"
        },
        {
            "code": "JE",
            "flag": "🇯🇪",
            "name": "Jersey",
            "tel": "+44-1534"
        },
        {
            "code": "JM",
            "flag": "🇯🇲",
            "name": "Jamaica",
            "tel": "+1-876"
        },
        {
            "code": "JO",
            "flag": "🇯🇴",
            "name": "Jordan",
            "tel": "+962"
        },
        {
            "code": "JP",
            "flag": "🇯🇵",
            "name": "Japan",
            "tel": "+81"
        },
        {
            "code": "KE",
            "flag": "🇰🇪",
            "name": "Kenya",
            "tel": "+254"
        },
        {
            "code": "KG",
            "flag": "🇰🇬",
            "name": "Kyrgyzstan",
            "tel": "+996"
        },
        {
            "code": "KH",
            "flag": "🇰🇭",
            "name": "Cambodia",
            "tel": "+855"
        },
        {
            "code": "KI",
            "flag": "🇰🇮",
            "name": "Kiribati",
            "tel": "+686"
        },
        {
            "code": "KM",
            "flag": "🇰🇲",
            "name": "Comoros",
            "tel": "+269"
        },
        {
            "code": "KN",
            "flag": "🇰🇳",
            "name": "Saint Kitts and Nevis",
            "tel": "+1-869"
        },
        {
            "code": "KP",
            "flag": "🇰🇵",
            "name": "North Korea",
            "tel": "+850"
        },
        {
            "code": "KR",
            "flag": "🇰🇷",
            "name": "South Korea",
            "tel": "+82"
        },
        {
            "code": "KW",
            "flag": "🇰🇼",
            "name": "Kuwait",
            "tel": "+965"
        },
        {
            "code": "KY",
            "flag": "🇰🇾",
            "name": "Cayman Islands",
            "tel": "+1-345"
        },
        {
            "code": "KZ",
            "flag": "🇰🇿",
            "name": "Kazakhstan",
            "tel": "+7"
        },
        {
            "code": "LA",
            "flag": "🇱🇦",
            "name": "Laos",
            "tel": "+856"
        },
        {
            "code": "LB",
            "flag": "🇱🇧",
            "name": "Lebanon",
            "tel": "+961"
        },
        {
            "code": "LC",
            "flag": "🇱🇨",
            "name": "Saint Lucia",
            "tel": "+1-758"
        },
        {
            "code": "LI",
            "flag": "🇱🇮",
            "name": "Liechtenstein",
            "tel": "+423"
        },
        {
            "code": "LK",
            "flag": "🇱🇰",
            "name": "Sri Lanka",
            "tel": "+94"
        },
        {
            "code": "LR",
            "flag": "🇱🇷",
            "name": "Liberia",
            "tel": "+231"
        },
        {
            "code": "LS",
            "flag": "🇱🇸",
            "name": "Lesotho",
            "tel": "+266"
        },
        {
            "code": "LT",
            "flag": "🇱🇹",
            "name": "Lithuania",
            "tel": "+370"
        },
        {
            "code": "LU",
            "flag": "🇱🇺",
            "name": "Luxembourg",
            "tel": "+352"
        },
        {
            "code": "LV",
            "flag": "🇱🇻",
            "name": "Latvia",
            "tel": "+371"
        },
        {
            "code": "LY",
            "flag": "🇱🇾",
            "name": "Libya",
            "tel": "+218"
        },
        {
            "code": "MA",
            "flag": "🇲🇦",
            "name": "Morocco",
            "tel": "+212"
        },
        {
            "code": "MC",
            "flag": "🇲🇨",
            "name": "Monaco",
            "tel": "+377"
        },
        {
            "code": "MD",
            "flag": "🇲🇩",
            "name": "Moldova",
            "tel": "+373"
        },
        {
            "code": "ME",
            "flag": "🇲🇪",
            "name": "Montenegro",
            "tel": "+382"
        },
        {
            "code": "MF",
            "flag": "🇲🇫",
            "name": "Saint Martin",
            "tel": "+590"
        },
        {
            "code": "MG",
            "flag": "🇲🇬",
            "name": "Madagascar",
            "tel": "+261"
        },
        {
            "code": "MH",
            "flag": "🇲🇭",
            "name": "Marshall Islands",
            "tel": "+692"
        },
        {
            "code": "MK",
            "flag": "🇲🇰",
            "name": "Macedonia",
            "tel": "+389"
        },
        {
            "code": "ML",
            "flag": "🇲🇱",
            "name": "Mali",
            "tel": "+223"
        },
        {
            "code": "MM",
            "flag": "🇲🇲",
            "name": "Myanmar",
            "tel": "+95"
        },
        {
            "code": "MN",
            "flag": "🇲🇳",
            "name": "Mongolia",
            "tel": "+976"
        },
        {
            "code": "MO",
            "flag": "🇲🇴",
            "name": "Macao",
            "tel": "+853"
        },
        {
            "code": "MP",
            "flag": "🇲🇵",
            "name": "Northern Mariana Islands",
            "tel": "+1-670"
        },
        {
            "code": "MQ",
            "flag": "🇲🇶",
            "name": "Martinique",
            "tel": "+596"
        },
        {
            "code": "MR",
            "flag": "🇲🇷",
            "name": "Mauritania",
            "tel": "+222"
        },
        {
            "code": "MS",
            "flag": "🇲🇸",
            "name": "Montserrat",
            "tel": "+1-664"
        },
        {
            "code": "MT",
            "flag": "🇲🇹",
            "name": "Malta",
            "tel": "+356"
        },
        {
            "code": "MU",
            "flag": "🇲🇺",
            "name": "Mauritius",
            "tel": "+230"
        },
        {
            "code": "MV",
            "flag": "🇲🇻",
            "name": "Maldives",
            "tel": "+960"
        },
        {
            "code": "MW",
            "flag": "🇲🇼",
            "name": "Malawi",
            "tel": "+265"
        },
        {
            "code": "MX",
            "flag": "🇲🇽",
            "name": "Mexico",
            "tel": "+52"
        },
        {
            "code": "MY",
            "flag": "🇲🇾",
            "name": "Malaysia",
            "tel": "+60"
        },
        {
            "code": "MZ",
            "flag": "🇲🇿",
            "name": "Mozambique",
            "tel": "+258"
        },
        {
            "code": "NA",
            "flag": "🇳🇦",
            "name": "Namibia",
            "tel": "+264"
        },
        {
            "code": "NC",
            "flag": "🇳🇨",
            "name": "New Caledonia",
            "tel": "+687"
        },
        {
            "code": "NE",
            "flag": "🇳🇪",
            "name": "Niger",
            "tel": "+227"
        },
        {
            "code": "NF",
            "flag": "🇳🇫",
            "name": "Norfolk Island",
            "tel": "+672"
        },
        {
            "code": "NG",
            "flag": "🇳🇬",
            "name": "Nigeria",
            "tel": "+234"
        },
        {
            "code": "NI",
            "flag": "🇳🇮",
            "name": "Nicaragua",
            "tel": "+505"
        },
        {
            "code": "NL",
            "flag": "🇳🇱",
            "name": "Netherlands",
            "tel": "+31"
        },
        {
            "code": "NO",
            "flag": "🇳🇴",
            "name": "Norway",
            "tel": "+47"
        },
        {
            "code": "NP",
            "flag": "🇳🇵",
            "name": "Nepal",
            "tel": "+977"
        },
        {
            "code": "NR",
            "flag": "🇳🇷",
            "name": "Nauru",
            "tel": "+674"
        },
        {
            "code": "NU",
            "flag": "🇳🇺",
            "name": "Niue",
            "tel": "+683"
        },
        {
            "code": "NZ",
            "flag": "🇳🇿",
            "name": "New Zealand",
            "tel": "+64"
        },
        {
            "code": "OM",
            "flag": "🇴🇲",
            "name": "Oman",
            "tel": "+968"
        },
        {
            "code": "PA",
            "flag": "🇵🇦",
            "name": "Panama",
            "tel": "+507"
        },
        {
            "code": "PE",
            "flag": "🇵🇪",
            "name": "Peru",
            "tel": "+51"
        },
        {
            "code": "PF",
            "flag": "🇵🇫",
            "name": "French Polynesia",
            "tel": "+689"
        },
        {
            "code": "PG",
            "flag": "🇵🇬",
            "name": "Papua New Guinea",
            "tel": "+675"
        },
        {
            "code": "PH",
            "flag": "🇵🇭",
            "name": "Philippines",
            "tel": "+63"
        },
        {
            "code": "PK",
            "flag": "🇵🇰",
            "name": "Pakistan",
            "tel": "+92"
        },
        {
            "code": "PL",
            "flag": "🇵🇱",
            "name": "Poland",
            "tel": "+48"
        },
        {
            "code": "PM",
            "flag": "🇵🇲",
            "name": "Saint Pierre and Miquelon",
            "tel": "+508"
        },
        {
            "code": "PN",
            "flag": "🇵🇳",
            "name": "Pitcairn",
            "tel": "+870"
        },
        {
            "code": "PR",
            "flag": "🇵🇷",
            "name": "Puerto Rico",
            "tel": "+1-787 and 1-939"
        },
        {
            "code": "PS",
            "flag": "🇵🇸",
            "name": "Palestinian Territory",
            "tel": "+970"
        },
        {
            "code": "PT",
            "flag": "🇵🇹",
            "name": "Portugal",
            "tel": "+351"
        },
        {
            "code": "PW",
            "flag": "🇵🇼",
            "name": "Palau",
            "tel": "+680"
        },
        {
            "code": "PY",
            "flag": "🇵🇾",
            "name": "Paraguay",
            "tel": "+595"
        },
        {
            "code": "QA",
            "flag": "🇶🇦",
            "name": "Qatar",
            "tel": "+974"
        },
        {
            "code": "RE",
            "flag": "🇷🇪",
            "name": "Reunion",
            "tel": "+262"
        },
        {
            "code": "RO",
            "flag": "🇷🇴",
            "name": "Romania",
            "tel": "+40"
        },
        {
            "code": "RS",
            "flag": "🇷🇸",
            "name": "Serbia",
            "tel": "+381"
        },
        {
            "code": "RU",
            "flag": "🇷🇺",
            "name": "Russia",
            "tel": "+7"
        },
        {
            "code": "RW",
            "flag": "🇷🇼",
            "name": "Rwanda",
            "tel": "+250"
        },
        {
            "code": "SA",
            "flag": "🇸🇦",
            "name": "Saudi Arabia",
            "tel": "+966"
        },
        {
            "code": "SB",
            "flag": "🇸🇧",
            "name": "Solomon Islands",
            "tel": "+677"
        },
        {
            "code": "SC",
            "flag": "🇸🇨",
            "name": "Seychelles",
            "tel": "+248"
        },
        {
            "code": "SD",
            "flag": "🇸🇩",
            "name": "Sudan",
            "tel": "+249"
        },
        {
            "code": "SE",
            "flag": "🇸🇪",
            "name": "Sweden",
            "tel": "+46"
        },
        {
            "code": "SG",
            "flag": "🇸🇬",
            "name": "Singapore",
            "tel": "+65"
        },
        {
            "code": "SH",
            "flag": "🇸🇭",
            "name": "Saint Helena",
            "tel": "+290"
        },
        {
            "code": "SI",
            "flag": "🇸🇮",
            "name": "Slovenia",
            "tel": "+386"
        },
        {
            "code": "SJ",
            "flag": "🇸🇯",
            "name": "Svalbard and Jan Mayen",
            "tel": "+47"
        },
        {
            "code": "SK",
            "flag": "🇸🇰",
            "name": "Slovakia",
            "tel": "+421"
        },
        {
            "code": "SL",
            "flag": "🇸🇱",
            "name": "Sierra Leone",
            "tel": "+232"
        },
        {
            "code": "SM",
            "flag": "🇸🇲",
            "name": "San Marino",
            "tel": "+378"
        },
        {
            "code": "SN",
            "flag": "🇸🇳",
            "name": "Senegal",
            "tel": "+221"
        },
        {
            "code": "SO",
            "flag": "🇸🇴",
            "name": "Somalia",
            "tel": "+252"
        },
        {
            "code": "SR",
            "flag": "🇸🇷",
            "name": "Suriname",
            "tel": "+597"
        },
        {
            "code": "SS",
            "flag": "🇸🇸",
            "name": "South Sudan",
            "tel": "+211"
        },
        {
            "code": "ST",
            "flag": "🇸🇹",
            "name": "Sao Tome and Principe",
            "tel": "+239"
        },
        {
            "code": "SV",
            "flag": "🇸🇻",
            "name": "El Salvador",
            "tel": "+503"
        },
        {
            "code": "SX",
            "flag": "🇸🇽",
            "name": "Sint Maarten",
            "tel": "+599"
        },
        {
            "code": "SY",
            "flag": "🇸🇾",
            "name": "Syria",
            "tel": "+963"
        },
        {
            "code": "SZ",
            "flag": "🇸🇿",
            "name": "Swaziland",
            "tel": "+268"
        },
        {
            "code": "TC",
            "flag": "🇹🇨",
            "name": "Turks and Caicos Islands",
            "tel": "+1-649"
        },
        {
            "code": "TD",
            "flag": "🇹🇩",
            "name": "Chad",
            "tel": "+235"
        },
        {
            "code": "TF",
            "flag": "🇹🇫",
            "name": "French Southern Territories",
            "tel": "+262"
        },
        {
            "code": "TG",
            "flag": "🇹🇬",
            "name": "Togo",
            "tel": "+228"
        },
        {
            "code": "TH",
            "flag": "🇹🇭",
            "name": "Thailand",
            "tel": "+66"
        },
        {
            "code": "TJ",
            "flag": "🇹🇯",
            "name": "Tajikistan",
            "tel": "+992"
        },
        {
            "code": "TK",
            "flag": "🇹🇰",
            "name": "Tokelau",
            "tel": "+690"
        },
        {
            "code": "TL",
            "flag": "🇹🇱",
            "name": "East Timor",
            "tel": "+670"
        },
        {
            "code": "TM",
            "flag": "🇹🇲",
            "name": "Turkmenistan",
            "tel": "+993"
        },
        {
            "code": "TN",
            "flag": "🇹🇳",
            "name": "Tunisia",
            "tel": "+216"
        },
        {
            "code": "TO",
            "flag": "🇹🇴",
            "name": "Tonga",
            "tel": "+676"
        },
        {
            "code": "TR",
            "flag": "🇹🇷",
            "name": "Turkey",
            "tel": "+90"
        },
        {
            "code": "TT",
            "flag": "🇹🇹",
            "name": "Trinidad and Tobago",
            "tel": "+1-868"
        },
        {
            "code": "TV",
            "flag": "🇹🇻",
            "name": "Tuvalu",
            "tel": "+688"
        },
        {
            "code": "TW",
            "flag": "🇹🇼",
            "name": "Taiwan",
            "tel": "+886"
        },
        {
            "code": "TZ",
            "flag": "🇹🇿",
            "name": "Tanzania",
            "tel": "+255"
        },
        {
            "code": "UA",
            "flag": "🇺🇦",
            "name": "Ukraine",
            "tel": "+380"
        },
        {
            "code": "UG",
            "flag": "🇺🇬",
            "name": "Uganda",
            "tel": "+256"
        },
        {
            "code": "UM",
            "flag": "🇺🇲",
            "name": "United States Minor Outlying Islands",
            "tel": "+1"
        },
        {
            "code": "US",
            "flag": "🇺🇸",
            "name": "United States",
            "tel": "+1"
        },
        {
            "code": "UY",
            "flag": "🇺🇾",
            "name": "Uruguay",
            "tel": "+598"
        },
        {
            "code": "UZ",
            "flag": "🇺🇿",
            "name": "Uzbekistan",
            "tel": "+998"
        },
        {
            "code": "VA",
            "flag": "🇻🇦",
            "name": "Vatican",
            "tel": "+379"
        },
        {
            "code": "VC",
            "flag": "🇻🇨",
            "name": "Saint Vincent and the Grenadines",
            "tel": "+1-784"
        },
        {
            "code": "VE",
            "flag": "🇻🇪",
            "name": "Venezuela",
            "tel": "+58"
        },
        {
            "code": "VG",
            "flag": "🇻🇬",
            "name": "British Virgin Islands",
            "tel": "+1-284"
        },
        {
            "code": "VI",
            "flag": "🇻🇮",
            "name": "U.S. Virgin Islands",
            "tel": "+1-340"
        },
        {
            "code": "VN",
            "flag": "🇻🇳",
            "name": "Vietnam",
            "tel": "+84"
        },
        {
            "code": "VU",
            "flag": "🇻🇺",
            "name": "Vanuatu",
            "tel": "+678"
        },
        {
            "code": "WF",
            "flag": "🇼🇫",
            "name": "Wallis and Futuna",
            "tel": "+681"
        },
        {
            "code": "WS",
            "flag": "🇼🇸",
            "name": "Samoa",
            "tel": "+685"
        },
        {
            "code": "YE",
            "flag": "🇾🇪",
            "name": "Yemen",
            "tel": "+967"
        },
        {
            "code": "YT",
            "flag": "🇾🇹",
            "name": "Mayotte",
            "tel": "+262"
        },
        {
            "code": "ZA",
            "flag": "🇿🇦",
            "name": "South Africa",
            "tel": "+27"
        },
        {
            "code": "ZM",
            "flag": "🇿🇲",
            "name": "Zambia",
            "tel": "+260"
        },
        {
            "code": "ZW",
            "flag": "🇿🇼",
            "name": "Zimbabwe",
            "tel": "+263"
        }
        ]
        let telPrefixes = ``;
        let countryOptions = ``;
        TelData.forEach(item => {
            telPrefixes += `<option value="${item.code}" ${item.code === 'AE' ? 'selected' : ''} >${item.flag} ${item.tel}</option>`;
            countryOptions += `<option value="${item.code}">${item.flag} ${item.name}</option>`;
        })
        document.getElementById('TelPrefix').innerHTML = telPrefixes;

    }
    bindTelephoneInput();
</script>

