<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Hyva Compatibility
 */

use Amasty\RequestQuote\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full lg:w-1/4 float-left lg:float-right lg:order-2 top-0 lg:sticky">
    <!-- <div class="flex pb-3 my-2 border-b-2 border-gray-300 flex-col">
        <h2 class="w-full text-2xl text-center text-gray-900 title-font font-base md:text-left">
            <? /* = $escaper->escapeHtml(__('Quote Summary')) */ ?>
        </h2>
    </div> -->
    <?= $block->getChildHtml('cart.summary') ?>
</div>
<div class="w-full lg:w-3/4 float-left lg:order-1 lg:pr-8">
    <?= $block->getChildHtml('form_before') ?>
    <?= $block->getChildHtml('cart-items') ?>
    <?= $block->getChildHtml('checkout_cart_widget') ?>
</div>
<div class="w-full lg:w-3/4 lg:pr-8">
    <?= $block->getChildHtml('cart.discount') ?>
</div>

