<div class="flex-shrink-0 z-20 order-2 w-auto navigation hidden lg:flex">
    <!-- desktop -->
    <div>
        <nav>
            <ul class="flex flex-wrap" id="menu-desktop">
                <div class="level-0 flex items-center mx-2 transition transition-colors duration-500 group/parent xl:mx-4">
                    <a href="https://bizaar-qa.magentoprojects.net/categories" title="Categories" class="main-menu-link level-0 block px-2 text-base clear text-black whitespace-nowrap font-regular">
                        <span>Categories</span>
                    </a>

                    <!-- <span class="inline items-center">
                                <?/*= $heroiconsSolid->chevronDownHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) */?>
                            </span> -->
                    <span class="inline items-center leading-3">
                        <i class="icon-arrow-down text-xs"></i>
                    </span>

                    <div
                        class="menu-sub lavel01 absolute left-0 top-full z-10 -mt-3 w-full opacity-0 transition-opacity ease-out pointer-events-none group-hover/parent:opacity-100 focus-within:opacity-0 group-hover/parent:pointer-events-auto open-firstmenu"
                    >
                        <div class="menu-inner mx-auto bg-white relative min-h-screen-50 bg-[#F8F8F8] shadow">
                            <div class="container relative">
                                <ul class="w-52 py-5 md:max-h-[280px] xl:max-h-[350px] overflow-y-auto">
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/categories/computers" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Computers </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/computers/laptops"
                                                        title="Laptops"
                                                        class="level-1 p-1 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Laptops
                                                    </a>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Networking Hardware </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points"
                                                        title="Access Points"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Access Points
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-4-b-g-n"
                                                                title="Wi-Fi 4 (B/G/N)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 4 (B/G/N)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-5-ac"
                                                                title="Wi-Fi 5 (AC)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 5 (AC)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-6-ax"
                                                                title="Wi-Fi 6 (AX)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 6 (AX)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-adapters-extenders"
                                                                title="Wi-Fi Adapters &amp; Extenders"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Adapters &amp; Extenders
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas"
                                                        title="Antennas"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Antennas
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/horn-antennas"
                                                                title="Horn Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Horn Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/omni-antennas"
                                                                title="Omni Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Omni Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/parabolic-dish-antennas"
                                                                title="Parabolic Dish Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Parabolic Dish Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/sector-antennas"
                                                                title="Sector Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Sector Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/twistport-adaptors"
                                                                title="Twistport Adaptors"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Twistport Adaptors
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks"
                                                        title="Fiber Networks"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Fiber Networks
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks/sfp-modules"
                                                                title="SFP Modules"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                SFP Modules
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems"
                                                        title="ISP Wireless Systems"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        ISP Wireless Systems
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/carrier-backhaul"
                                                                title="Carrier Backhaul"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Carrier Backhaul
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/integrated-cpe"
                                                                title="Integrated CPE"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Integrated CPE
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/integrated-sector"
                                                                title="Integrated Sector"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Integrated Sector
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/outdoor-radio"
                                                                title="Outdoor Radio"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Outdoor Radio
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers"
                                                        title="Routers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Routers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/4g-lte-5g-wi-fi-routers"
                                                                title="4G/LTE/5G Wi-Fi Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                4G/LTE/5G Wi-Fi Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/adsl-routers"
                                                                title="ADSL Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                ADSL Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/cloud-core-routers"
                                                                title="Cloud Core Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Cloud Core Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/ethernet-routers"
                                                                title="Ethernet Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Ethernet Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/other-routers"
                                                                title="Other Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Other Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/wi-fi-routers"
                                                                title="Wi-Fi Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Routers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches"
                                                        title="Switches"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Switches
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/industrial-switches"
                                                                title="Industrial Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Industrial Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-poe-switches"
                                                                title="Managed PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-switches"
                                                                title="Managed Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/os-consoles-controllers"
                                                                title="OS Consoles &amp; Controllers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                OS Consoles &amp; Controllers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-poe-switches"
                                                                title="Unmanaged PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-switches"
                                                                title="Unmanaged Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged Switches
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Printers &amp; Scanners </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers"
                                                        title="Printers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Printers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/inkjet-printers"
                                                                title="Inkjet Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Inkjet Printers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/inktank-printers"
                                                                title="Inktank Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Inktank Printers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/laser-printers"
                                                                title="Laser Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Laser Printers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/special-format-printers"
                                                        title="Special Format Printers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Special Format Printers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/special-format-printers/dot-matrix-printers"
                                                                title="Dot Matrix Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Dot Matrix Printers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/special-format-printers/thermal-printers-pos"
                                                                title="Thermal Printers &amp; POS"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Thermal Printers &amp; POS
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="level-0 flex items-center mx-2 transition transition-colors duration-500 group/parent xl:mx-4">
                    <a href="https://bizaar-qa.magentoprojects.net/brands" title="Brands" class="main-menu-link level-0 block px-2 text-base clear text-black whitespace-nowrap font-regular">
                        <span>Brands</span>
                    </a>

                    <!-- <span class="inline items-center">
                                <?/*= $heroiconsSolid->chevronDownHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) */?>
                            </span> -->
                    <span class="inline items-center leading-3">
                        <i class="icon-arrow-down text-xs"></i>
                    </span>

                    <div
                        class="menu-sub lavel01 absolute left-0 top-full z-10 -mt-3 w-full opacity-0 transition-opacity ease-out pointer-events-none group-hover/parent:opacity-100 focus-within:opacity-0 group-hover/parent:pointer-events-auto open-firstmenu"
                    >
                        <div class="menu-inner mx-auto bg-white relative min-h-screen-50 bg-[#F8F8F8] shadow">
                            <div class="container relative">
                                <ul class="w-52 py-5 md:max-h-[280px] xl:max-h-[350px] overflow-y-auto">
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/aruba-instant-on" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Aruba Instant On </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks"
                                                        title="Fiber Networks"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Fiber Networks
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks/sfp-modules"
                                                                title="SFP Modules"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                SFP Modules
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points"
                                                        title="Access Points"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Access Points
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-6-ax"
                                                                title="Wi-Fi 6 (AX)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 6 (AX)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-5-ac"
                                                                title="Wi-Fi 5 (AC)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 5 (AC)
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches"
                                                        title="Switches"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Switches
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-switches"
                                                                title="Unmanaged Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-poe-switches"
                                                                title="Unmanaged PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-switches"
                                                                title="Managed Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-poe-switches"
                                                                title="Managed PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/industrial-switches"
                                                                title="Industrial Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Industrial Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/os-consoles-controllers"
                                                                title="OS Consoles &amp; Controllers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                OS Consoles &amp; Controllers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/mikrotik" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> MikroTik </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks"
                                                        title="Fiber Networks"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Fiber Networks
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks/sfp-modules"
                                                                title="SFP Modules"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                SFP Modules
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points"
                                                        title="Access Points"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Access Points
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-6-ax"
                                                                title="Wi-Fi 6 (AX)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 6 (AX)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-5-ac"
                                                                title="Wi-Fi 5 (AC)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 5 (AC)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-4-b-g-n"
                                                                title="Wi-Fi 4 (B/G/N)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 4 (B/G/N)
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches"
                                                        title="Switches"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Switches
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-switches"
                                                                title="Unmanaged Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-poe-switches"
                                                                title="Unmanaged PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-switches"
                                                                title="Managed Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-poe-switches"
                                                                title="Managed PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/industrial-switches"
                                                                title="Industrial Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Industrial Switches
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems"
                                                        title="ISP Wireless Systems"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        ISP Wireless Systems
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/integrated-cpe"
                                                                title="Integrated CPE"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Integrated CPE
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/outdoor-radio"
                                                                title="Outdoor Radio"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Outdoor Radio
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas"
                                                        title="Antennas"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Antennas
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/parabolic-dish-antennas"
                                                                title="Parabolic Dish Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Parabolic Dish Antennas
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers"
                                                        title="Routers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Routers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/ethernet-routers"
                                                                title="Ethernet Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Ethernet Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/cloud-core-routers"
                                                                title="Cloud Core Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Cloud Core Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/wi-fi-routers"
                                                                title="Wi-Fi Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Routers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/power-solutions/poe"
                                                        title="PoE"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        PoE
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/power-solutions/poe/poe-injectors"
                                                                title="PoE Injectors"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                PoE Injectors
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/hp" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> HP </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers"
                                                        title="Printers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Printers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/laser-printers"
                                                                title="Laser Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Laser Printers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/computers/laptops"
                                                        title="Laptops"
                                                        class="level-1 p-1 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Laptops
                                                    </a>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/canon" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Canon </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers"
                                                        title="Printers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Printers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/laser-printers"
                                                                title="Laser Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Laser Printers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/inkjet-printers"
                                                                title="Inkjet Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Inkjet Printers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/epson" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Epson </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers"
                                                        title="Printers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Printers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/printers/inkjet-printers"
                                                                title="Inkjet Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Inkjet Printers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/special-format-printers"
                                                        title="Special Format Printers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Special Format Printers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/printers-scanners/special-format-printers/dot-matrix-printers"
                                                                title="Dot Matrix Printers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Dot Matrix Printers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/rf-elements" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> RF Elements </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas"
                                                        title="Antennas"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Antennas
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/parabolic-dish-antennas"
                                                                title="Parabolic Dish Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Parabolic Dish Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/twistport-adaptors"
                                                                title="Twistport Adaptors"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Twistport Adaptors
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/sector-antennas"
                                                                title="Sector Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Sector Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/horn-antennas"
                                                                title="Horn Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Horn Antennas
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/ubiquiti" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Ubiquiti </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks"
                                                        title="Fiber Networks"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Fiber Networks
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks/sfp-modules"
                                                                title="SFP Modules"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                SFP Modules
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points"
                                                        title="Access Points"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Access Points
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-6-ax"
                                                                title="Wi-Fi 6 (AX)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 6 (AX)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-5-ac"
                                                                title="Wi-Fi 5 (AC)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 5 (AC)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-adapters-extenders"
                                                                title="Wi-Fi Adapters &amp; Extenders"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Adapters &amp; Extenders
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches"
                                                        title="Switches"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Switches
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-switches"
                                                                title="Unmanaged Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-switches"
                                                                title="Managed Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-poe-switches"
                                                                title="Managed PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/industrial-switches"
                                                                title="Industrial Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Industrial Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/os-consoles-controllers"
                                                                title="OS Consoles &amp; Controllers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                OS Consoles &amp; Controllers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems"
                                                        title="ISP Wireless Systems"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        ISP Wireless Systems
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/integrated-cpe"
                                                                title="Integrated CPE"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Integrated CPE
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/outdoor-radio"
                                                                title="Outdoor Radio"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Outdoor Radio
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/integrated-sector"
                                                                title="Integrated Sector"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Integrated Sector
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/isp-wireless-systems/carrier-backhaul"
                                                                title="Carrier Backhaul"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Carrier Backhaul
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas"
                                                        title="Antennas"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Antennas
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/parabolic-dish-antennas"
                                                                title="Parabolic Dish Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Parabolic Dish Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/sector-antennas"
                                                                title="Sector Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Sector Antennas
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/antennas/omni-antennas"
                                                                title="Omni Antennas"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Omni Antennas
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers"
                                                        title="Routers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Routers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/ethernet-routers"
                                                                title="Ethernet Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Ethernet Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/other-routers"
                                                                title="Other Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Other Routers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/power-solutions/poe"
                                                        title="PoE"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        PoE
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/power-solutions/poe/poe-injectors"
                                                                title="PoE Injectors"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                PoE Injectors
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/ruijie" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Ruijie </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks"
                                                        title="Fiber Networks"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Fiber Networks
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks/sfp-modules"
                                                                title="SFP Modules"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                SFP Modules
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points"
                                                        title="Access Points"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Access Points
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-6-ax"
                                                                title="Wi-Fi 6 (AX)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 6 (AX)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-5-ac"
                                                                title="Wi-Fi 5 (AC)"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi 5 (AC)
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-adapters-extenders"
                                                                title="Wi-Fi Adapters &amp; Extenders"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Adapters &amp; Extenders
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches"
                                                        title="Switches"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Switches
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-switches"
                                                                title="Unmanaged Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-poe-switches"
                                                                title="Unmanaged PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-switches"
                                                                title="Managed Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-poe-switches"
                                                                title="Managed PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed PoE Switches
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers"
                                                        title="Routers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Routers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/ethernet-routers"
                                                                title="Ethernet Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Ethernet Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/wi-fi-routers"
                                                                title="Wi-Fi Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/other-routers"
                                                                title="Other Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Other Routers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/cudy" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Cudy </a>
                                        <!-- <span class="inline-block z-10 relative py-2 px-2">
                                                        <?//= $heroiconsSolid->chevronRightHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' => 'true']) ?>
                                                    </span> -->
                                        <div
                                            class="flex lavel02 container left-0 absolute w-full min-h-full top-0 opacity-0 focus-within:opacity-100 group-hover/child:opacity-100 pointer-events-none group-hover/child:pointer-events-auto pt-3 pb-2"
                                        >
                                            <ul class="ipad-scroll-fix ml-52 grid flex-1 grid-cols-2 xl:grid-cols-4 gap-y-2 gap-x-8 px-4 pt-0 pb-2 border-l-[#E4E4E4] border-l border-solid h-fit">
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks"
                                                        title="Fiber Networks"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Fiber Networks
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/fiber-networks/sfp-modules"
                                                                title="SFP Modules"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                SFP Modules
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points"
                                                        title="Access Points"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Access Points
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/access-points/wi-fi-adapters-extenders"
                                                                title="Wi-Fi Adapters &amp; Extenders"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Adapters &amp; Extenders
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches"
                                                        title="Switches"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Switches
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-switches"
                                                                title="Unmanaged Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/unmanaged-poe-switches"
                                                                title="Unmanaged PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Unmanaged PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-switches"
                                                                title="Managed Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/managed-poe-switches"
                                                                title="Managed PoE Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Managed PoE Switches
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/switches/industrial-switches"
                                                                title="Industrial Switches"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Industrial Switches
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="level-1 min-w-48">
                                                    <a
                                                        href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers"
                                                        title="Routers"
                                                        class="level-1 py-1 px-2 block text-base font-semibold leading-loose hover:underline clear text-black"
                                                    >
                                                        Routers
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/wi-fi-routers"
                                                                title="Wi-Fi Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                Wi-Fi Routers
                                                            </a>
                                                        </li>
                                                        <li class="level-2">
                                                            <a
                                                                href="https://bizaar-qa.magentoprojects.net/categories/networking-hardware/routers/4g-lte-5g-wi-fi-routers"
                                                                title="4G/LTE/5G Wi-Fi Routers"
                                                                class="level-2 py-0.5 px-2 block text-lg md:text-sm hover:underline clear text-black"
                                                            >
                                                                4G/LTE/5G Wi-Fi Routers
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                            <ul class="k max-w-sm p-5">
                                                <li><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sub-menu-image')->toHtml();?></li>
                                            </ul>
                                        </div>
                                    </li>
                                    <li class="group/child flex justify-between items-center w-full">
                                        <a href="https://bizaar-qa.magentoprojects.net/brands/slim" class="w-full py-1 px-2 z-10 relative break-words clear font-semibold"> Slim </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="level-0 flex items-center mx-2 transition transition-colors duration-500 group/parent xl:mx-4">
                    <a href="https://bizaar-qa.magentoprojects.net/catalog/category/view/s/sale/id/765/" title="Sale" class="main-menu-link level-0 block px-2 text-base clear text-black whitespace-nowrap font-regular">
                        <span>Sale</span>
                    </a>
                </div>
            </ul>
        </nav>
    </div>
</div>
