<?php
/** @var Infibeam\Ccavenue\Block\Transparent\Redirect $block */
$params = $block->getPostParams();
$redirectUrl = $block->getRedirectUrl();
?>
<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head><title></title></head>
<body onload="document.forms['proxy_form'].submit()">
<form id="proxy_form" action="<?= $block->escapeUrl($redirectUrl) ?>"
      method="POST" >
    <?php foreach ($params as $name => $value):?>
        <input value="<?= $block->escapeHtml($value) ?>" name="<?= $block->escapeHtml($name) ?>" type="hidden"/>
    <?php endforeach?>
</body>
</html>