<?php

/**
 * Magedelight
 *
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
 
if ($block->getRefundData()!=NULL) {
    $data = json_encode($block->getRefundData());?>
    <script type="text/javascript">
     require(['jquery'],function ($) {
      	var finalData = <?= $data;?>;
        dataLayer.push({ ecommerce: null }); 
        window.dataLayer.push(finalData);
     });
  </script>
<?php  $block->setRefundData(); ?>
<?php } ?>