<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */

/**
 * @var $helper Magedelight\Ga4\Helper\Data
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>

<?php
$helper = $block->dataHelper();
$cookieConcent = $helper->getCookie();
$accessible = 1;
if ($helper->getGDPRStatus()) {
    if (isset($cookieConcent)) {
        $accessible = 1;
    } else {
        $accessible = 0;
    }
}
?>
<?php if ($helper->isGTMStatus() && $accessible == 1): ?>
    <!-- Start of MageDelight GA4 Extension -->
    <?= $helper->getGTMJSCode(); ?>
    <?php if ($helper->getGaStatus()): ?>
        <?= $helper->getGADRemarketing(); ?>
        <?= $helper->getGADJSCode(); ?>
    <?php endif; ?>
    <!-- End of MageDelight GA4 Extension -->
<?php endif; ?>

