<?php
/**
 * Magedelight
 *
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */

/**
 * @var \Magedelight\Ga4\Block\Adminhtml\View $block
 */
$rowData = $block->rowData();
?>
<table class="data-grid data-grid-draggable">
    <thead>
        <tr class="data-row">
            <th class="data-grid-th">
                <?php echo __('Key'); ?> 
            </th>
            <th class="data-grid-th">
                <?php echo __('Value'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="data-row">
            <td>
                <?php echo __('Page URL'); ?>
            </td>
            <td>
                <?php echo $rowData['pageUrl']; ?>
            </td>
        </tr>    
        <tr class="data-row _odd-row">
            <td>
                <?php echo __('Data'); ?>
            </td>
            <td>
                <textarea class="prettyJSONFormat" id="detail-view-<?php echo $rowData['entityId']; ?>" cols=100 rows=15 readonly><?php echo $rowData['eventData']; ?></textarea>
            </td>
        </tr>
    </tbody>
</table>