<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>

<?php $_helper = $block->dataHelper();
$cookieConcent = $_helper->getCookie();
$accessible = 1;
if ($_helper->getGDPRStatus()) {
    if (isset($cookieConcent)) {
        $accessible = 1;
    } else {
        $accessible = 0;
    }
}
?>
<?php if ($_helper->isGTMStatus() && $accessible == 1): ?>
    <!-- Start of MageDelight GA4 Extension -->
    <script>
        require(['jquery','magedelight_gtagLayer', 'Magento_Customer/js/customer-data'],
            function ($, mdPersL, customerData) {
                $(document).ajaxComplete(function( event, xhr, settings ) {
                    if (settings.url.search('/customer\/section\/load/') > 0) {
                        var response = xhr.responseJSON;
                        if (response.ga4) {
                            var dataLayerData = $.parseJSON(response.ga4.datalayer);
                            for (index in dataLayerData) {
                                dataLayer.push({ ecommerce: null }); 
                                window.dataLayer.push(dataLayerData[index]);
                            }
                        }
                    }
                });
                var mdPersLOptions={'storageDataExpiryTime' : <?=/* @noEscape */  $_helper->getDataStorageExpiryTime() ?> };
                mdPersL.init(mdPersLOptions);
            });
    </script>
    <?php if ($_helper->getPromotionTracking()): ?>
        <?php $url = $this->getUrl('ga4/index/item');?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magedelight_Ga4/js/magedelight_ga4" : {
                    "customurl" : "<?= $block->escapeJs($url); ?>",
                    "view_promotion" : "<?= $block->escapeJs($_helper->GTMEventConfigured('view_promotion')); ?>",
                    "select_promotion" : "<?= $block->escapeJs($_helper->GTMEventConfigured('select_promotion')); ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
    <!-- End of MageDelight GA4 Extension -->
<?php endif; ?>
