<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>

<?php
if ($block->isGTMStatus()) {
   /* $helper = $block->dataHelper();
    $code = $helper->getCurrencyCode();
    $items = $block->getCheckoutItems();
    $productCollection = [];
    $productCollection['contentScope'] =
    [
        'step' => '1',
        'option' => ''
    ];
    $productCollection['products'] = $items;
    $productCollection['currencyCode'] = $code;
    $block->setEventValues('event', 'add_shipping_info');
    $block->setEventValues('eventLabel', 'Add Shipping Info');
    $block->setPurchaseData('checkout', $productCollection);

    $dataevent =[
        'event' => 'add_shipping_info',
        'eventLabel' => 'Add Shipping Info',
        'currencyCode'=> $productCollection['currencyCode'],
        'products' => $items
    ];
    $helper->setTagManagerReportData($dataevent);*/

} ?>
