<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>

<?php
$helper = $block->dataHelper();
$cookieConcent = $helper->getCookie();
$accessible = 1;
if ($helper->getGDPRStatus()) {
    if (isset($cookieConcent)) {
        $accessible = 1;
    } else {
        $accessible = 0;
    }
}
if ($block->isGTMStatus() && $accessible == 1 && $helper->GTMEventConfigured('view_cart')) {
    $code = $helper->getCurrencyCode();
    $items = $block->getViewCartItems();
    $productCollection = [];
    /*$productCollection['contentScope'] =
    [
        'step' => '1',
        'option' => ''
    ];*/
    //$productCollection['products'] = $items;
    //$productCollection['currency'] = $code;
    $quote = $block->getQuote();
    $data = [];
    $data['currency'] = $code;
    if($quote->getGrandTotal()){
        $data['value'] = $block->getPurchaseAmount();
    }
    $data['items'] = $items;
    $block->setEventValues('event', 'view_cart');
    $block->setOrderPurchaseData($data);

    if (!empty($items)) {
        $dataevent =['event' => 'view_cart', 'ecommerce' => $data];
        $helper->setTagManagerReportData($dataevent);
    }
} ?>