<?php
/**
 * Magedelight
 * Copyright (C) 2023 Magedelight <info@Magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Ga4
 * @copyright Copyright (c) 2023 Mage Delight (http://www.Magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@Magedelight.com>
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$cataloghelper = $block->dataHelper();
$viewModel = $block->getData('selectItem');

if (!$_productCollection->count()) { ?>
    <div class="message info empty">
        <div><?= /* @noEscape */ __('We can\'t find products matching the selection.') ?>
        </div>
    </div>
<?php } else {
    /* @noEscape */ $block->getToolbarHtml();
    /* @noEscape */ $block->getAdditionalHtml();
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode; ?> products-<?= /* @noEscape */ $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php foreach ($_productCollection as $_product): ?>
                <?= ($iterator++ == 1) ?
                '<li class="item product product-item">' :
                '</li><li class="item product product-item">'
                ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <a <?= /* @noEscape */ $viewModel->selectItem($_product, $iterator-1); ?>
                            href="<?=/* @noEscape */ $_product->getProductUrl() ?>"
                             class="product photo product-item-photo" tabindex="-1">
                        <?=/* @noEscape */ $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a <?= /* @noEscape */ $viewModel->selectItem($_product, $iterator-1); ?>
                                class="product-item-link"
                                href="<?= /* @noEscape */$_product->getProductUrl() ?>">
                                <?=/* @noEscape */ $cataloghelper->productAttribute(
                                    $_product,
                                    $_product->getName(),
                                    'name'
                                ); ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */$block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?=/* @noEscape */ $block->getProductPrice($_product); ?>
                        <?=/* @noEscape */ $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions" >
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                        data-product-sku="<?=/* @noEscape */$block->escapeHtml($_product->getSku()) ?>" 
                                            action="<?= /* @noEscape */$postParams['action'] ?>" method="post">
                                            <input type="hidden" 
                                            name="product" 
                                            value="<?=/* @noEscape */ $postParams['data']['product']; ?>">
                                            <input 
                                            type="hidden"
                                            name="<?= /* @noEscape */Action::PARAM_NAME_URL_ENCODED; ?>"
                                value="<?=/* @noEscape */$postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?=/* @noEscape */ $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?=/* @noEscape */ $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?=/* @noEscape */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available">
                                                <span><?=/* @noEscape */ __('In stock') ?>
                                            </span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?=/* @noEscape */ __('Out of stock') ?>
                                            </span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary" >
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?=/* @noEscape */ $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?=/* @noEscape */ $cataloghelper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?=/* @noEscape */$_product->getProductUrl() ?>"
                                     title="<?=/* @noEscape */$_productNameStripped ?>"
                                       class="action more"><?=/* @noEscape */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= /* @noEscape */$block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                 "catalogAddToCart": {
                    "product_sku": "<?=/* @noEscape */ $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php } ?>
