#!/bin/bash

# If no arguments, just log into shell
if [ -t 0 ]; then
    d/docker-compose exec db mysql -umagento -pmagento magento
else
    # Read from stdin, ex: bin/mysql < dbdump.sql
    d/docker-compose exec -T db mysql -umagento -pmagento magento "$@"
fi
