<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Request a Quote Hyva Compatibility
 */

use Amasty\RequestQuoteHyva\ViewModel\Cart\Item;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/** @var Renderer $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
$itemViewModel = $viewModels->require(Item::class);
?>
<tbody class="cart item bg-white">
<tr class="item-info align-top flex flex-wrap lg:table-row">
    <td class="col item flex gap-4 text-left w-full lg:w-auto lg:pt-6 lg:px-4 lg:gap-6 lg:flex-col xl:flex-row">
        <?php if ($block->hasProductUrl()): ?>
            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
               title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
               tabindex="-1"
               class="product-item-photo flex-shrink-0">
        <?php else: ?>
            <span class="product-item-photo flex-shrink-0">
        <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        <?php if ($block->hasProductUrl()): ?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        <div class="product-item-details flex-grow">
            <strong class="product-item-name break-all">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"><?= $escaper->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $escaper->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($options = $block->getOptionList()): ?>
                <dl class="item-options w-full break-all mt-4 pb-1 text-sm clearfix">
                    <?php foreach ($options as $option): ?>
                        <?php $formattedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dt class="font-bold float-left clear-left mr-2 mb-2"><?= $escaper->escapeHtml($option['label']) ?></dt>
                        <dd class="float-left">
                            <?php if (isset($formattedOptionValue['full_view'])): ?>
                                <?= $escaper->escapeHtml($formattedOptionValue['full_view']) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($formattedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <div x-cloak x-data="{isVisible: $el.querySelector('.add-note textarea').value.trim().length > 0 }" class="mt-3">
                <button @click.prevent="isVisible = true"
                   x-show="!isVisible"
                    role="button"
                   class="add-note-quote text-blue-600 hover:underline hover:cursor-pointer">
                    <?= $escaper->escapeHtml(__('Add Note')) ?>
                </button>
                <div class="add-note" x-show="isVisible">
                    <div class="control">
                    <textarea id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-note"
                              name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][note]"
                              class="form-input w-full"
                              aria-label="<?= $escaper->escapeHtml(__('Add Note')) ?>"
                              rows="3"
                              cols="25"
                              ><?= $escaper->escapeHtml($itemViewModel->retrieveCustomerNote($item->getAdditionalData())) ?></textarea>
                    </div>
                </div>
            </div>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>"><div><?= $escaper->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>
    <td class="col price pt-6 lg:pt-2 px-4 block w-full sm:w-1/3 lg:w-auto lg:table-cell">
        <span class="lg:hidden font-bold mt-2">
            <?= $escaper->escapeHtml(__('Price')) ?>
        </span>
        <?= $block->getUnitPriceHtml($item) ?>
    </td>
    <td class="col qty pt-6 lg:pt-2 px-4 block w-full sm:w-1/3 lg:w-auto lg:table-cell">
        <span class="lg:hidden font-bold">
            <?= $escaper->escapeHtml(__('Qty')) ?>
        </span>
        <div class="field qty">
            <div class="control qty">
                <label for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty">
                    <span class="label sr-only"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                    <input id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                           name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                           value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                           class="qty form-input px-2 py-2 w-20 text-center"
                           required="required"
                           min="0"/>
                </label>
            </div>
        </div>
    </td>

    <td class="col subtotal pt-6 px-4 block w-full sm:w-1/3 lg:w-auto lg:table-cell">
        <span class="lg:hidden font-bold">
            <?= $escaper->escapeHtml(__('Subtotal')) ?>
        </span>
        <?php if ((float) $item->getPrice() || $itemViewModel->isAllowCustomizePrice()): ?>
            <?= $block->getRowTotalHtml($item) ?>
        <?php else: ?>
            <?= $escaper->escapeHtml(__('N/A')) ?>
        <?php endif; ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="100">
        <div class="flex justify-end gap-4 p-4 pt-2">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </div>
    </td>
</tr>
</tbody>
