# This is a basic workflow to help you get started with Actions

name: Magento 2 Coding Standards Test
on: [pull_request]
jobs:
  build:
    name: Coding Standards Test
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate code directory
        run: |
          bash /home/ubuntu/phpcs-action/8.1/run.sh "$GITHUB_WORKSPACE/app/code/Magebit/ $GITHUB_WORKSPACE/app/design/frontend/Magebit/bizaar" $GITHUB_WORKSPACE/ "--standard=HyvaThemes --extensions=phtml,php"
          echo ::set-output name=findings::$(cat $GITHUB_WORKSPACE/phpcs-action.txt)
          echo ::set-output name=return-state::$(cat $GITHUB_WORKSPACE/phpcs-output.txt)
        id: phpcs-output

      - name: Add Comment
        uses: actions/github-script@v3
        if: steps.phpcs-output.outputs.return-state != '0'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.phpcs-output.outputs.findings }}'
            })

      - name: Validate luma theme
        run: |
          bash /home/ubuntu/phpcs-action/8.1/run.sh "$GITHUB_WORKSPACE/app/design/frontend/Magebit/bizaar_fallback" $GITHUB_WORKSPACE/ "--standard=Magento2 --extensions=phtml,php"
          echo ::set-output name=findings::$(cat $GITHUB_WORKSPACE/phpcs-action.txt)
          echo ::set-output name=return-state::$(cat $GITHUB_WORKSPACE/phpcs-output.txt)
        id: phpcs-luma-output

      - name: Add Comment
        uses: actions/github-script@v3
        if: steps.phpcs-luma-output.outputs.return-state != '0'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ steps.phpcs-luma-output.outputs.findings }}'
            })

      - name: Failed Check
        run: |
          if [[ "${{ steps.phpcs-output.outputs.return-state }}" != "0" ]] || [[ "${{ steps.phpcs-luma-output.outputs.return-state }}" != "0" ]]; then
            exit 1
          fi
