name: Code Analysis and Security Assessment

on:
  pull_request:
    branches:
      - development

defaults:
  run:
    working-directory: /var/www/html/bizaarci/webroot

env:
  CHANGE_BRANCH: ${{ github.event.pull_request.head.ref }}
  CHANGE_TARGET: ${{ github.event.pull_request.base.ref }}

jobs:
  php_static_analysis:
    runs-on: bizaarci
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHANGE_TARGET }}

      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHANGE_BRANCH }}

      - name: Determine Changed Files
        id: changes
        run: |
          changedFiles=$(git diff --name-only --diff-filter=ACMRT origin/${{ env.CHANGE_TARGET }}..origin/${{ env.CHANGE_BRANCH }})
          if [ -n "$changedFiles" ]; then
            CHANGED_FILES=$(echo "$changedFiles" | awk '{printf " --files %s", $0}')
            echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV
          else
            echo "No changed files in the pull request"
            echo "CHANGED_FILES=" >> $GITHUB_ENV
          fi
          echo "Changed Files: $CHANGED_FILES"

      - name: Composer Validation & Install
        run: |
          composer validate --ansi
          composer install --ansi --prefer-dist --no-suggest

      - name: Run ESLint in Batches (20 files per batch)
        if: always()
        run: |
          batch_size=20
          changedFiles=($CHANGED_FILES)
          for ((i=0; i<${#changedFiles[@]}; i+=batch_size)); do
            batch=()
            for file in "${changedFiles[@]:i:batch_size}"; do
              if [[ $file == *.js ]]; then
                batch+=("$file")
              fi
            done
            if [ ${#batch[@]} -gt 0 ]; then
              echo "Running ESLint on batch: ${batch[@]}"
              npm run eslint "${batch[@]}"
            fi
          done

      - name: Run PHP Code Sniffer for HyvaThemes Standard
        if: always()
        run: |
          changedFilesSpace=$(echo "$CHANGED_FILES" | sed 's/--files//g' | tr -s ' ')
          echo "Running PHP Code Sniffer for HyvaThemes standard on files: $changedFilesSpace"
          vendor/bin/phpcs --standard=HyvaThemes $changedFilesSpace -s

      - name: Run PHP Code Sniffer for Magento2 Standard
        if: always()
        run: |
          changedFilesSpace=$(echo "$CHANGED_FILES" | sed 's/--files//g' | tr -s ' ')
          echo "Running PHP Code Sniffer for Magento2 standard on files: $changedFilesSpace"
          vendor/bin/phpcs --standard=Magento2 $changedFilesSpace -s

      - name: PHP Mess Detector
        if: always()
        run: |
          changedFilesComma=$(echo "$CHANGED_FILES" | sed 's/--files//g' | tr ' ' ',' | sed 's/^,//')
          echo "Running PHP Mess Detector on files: $changedFilesComma"
          vendor/bin/phpmd $changedFilesComma ansi ./dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml
