name: Code Analysis and Security Assessment

on:
  pull_request:
    branches:
      - development

env:
  CHANGE_BRANCH: ${{ github.event.pull_request.head.ref }}
  CHANGE_TARGET: ${{ github.event.pull_request.base.ref }}

jobs:
  php_static_analysis:
    runs-on: bizaarci
    defaults:
      run:
        working-directory: /var/www/html/bizaarci/webroot
    steps:
      - name: Checkout Target repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Checkout Source repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check Directory Permissions
        run: |
          ls -ld /var/www/html/bizaarci/webroot/cibizaar/cibizaar
          whoami
      - name: Create Temporary Git Config
        run: |
          mkdir -p /tmp/git-config
          echo "[user]" > /tmp/git-config/config
          echo "name = GitHub Actions" >> /tmp/git-config/config
          echo "email = actions@github.com" >> /tmp/git-config/config
          git config --global --add include.path /tmp/git-config/config
      - name: Set CHANGED_FILES
        run: |
          cd $WORKSPACE
          echo 'pwd'
          changedFiles=$(git diff --name-only --diff-filter=ACMRT origin/${{ env.CHANGE_TARGET }}...origin/${{ env.CHANGE_BRANCH }})
          if [ ! -z "$changedFiles" ]; then
          CHANGED_FILES=$(echo "$changedFiles" | awk '{printf " --files %s", $0}')
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV
          else
            echo "No changed files in the pull request"
            echo "CHANGED_FILES=" >> $GITHUB_ENV
          fi
          echo $CHANGED_FILES
